### ISSUE TITLE
Does `@differentiable` and `gradient` work for `Tensor`?

### ISSUE THREAD

**Issue by xysun** [tensorflow/swift#101]
I was following the automatic differentiation example in the [design documentation](https://github.com/tensorflow/swift/blob/master/docs/DesignOverview.md#automatic-differentiation) and wanted to try out for `Tensor<T>` types so I can do automatic differentiation for matrices. Below is a minimal example that doesn't work: 

```swift
import TensorFlow
let a = Tensor<Float>([1.0,2.0])

@differentiable(adjoint: adjointF)
func f(_ x:Tensor<Float>) -> Float{
  return 1
}

// I tried not provide my own adjoint function and got same error as well
func adjointF(seed: Float, originalResult: Float, x:Tensor<Float>) -> Tensor<Float>{
  return Tensor<Float>([3.0,4.0])
}

print(f(a))
print(gradient(of: f)(a))

```

The main error is
```
SIL verification failed: Operand of release must have reference semantics: value->getType().isReferenceCounted(F.getModule())
```

Does this auto-diff api work right now or I shouldn't really do stuff like this? =]

**Comment by rxwei** [comment]
The design overview is very outdated. We'll update that soon.

The code you provided should work with the latest branch, and you don't need to provide any adjoint at all.

```swift
import TensorFlow
let a = Tensor<Float>([1.0,2.0])

func f(_ x:Tensor<Float>) -> Float{
  return 1
}

print(f(a))
print(gradient(of: f)(a))
```

```console
1.0
2019-01-24 14:42:34.051345: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 AVX512F FMA
0.0
```
