### ISSUE TITLE
issues with latest ubuntu pre-build package (DEVELOPMENT-2019-01-04)

### ISSUE THREAD

**Issue by zou000** [tensorflow/swift#103]
I tried out the package in a docker image (instruction here: https://github.com/zou000/swift-tensorflow/tree/update). And there are 2 problems:
* swift needs `libBlocksRuntime.so.0` but it only has `libBlocksRuntime.so`, so I have to do `mv -n /usr/lib/libBlocksRuntime.so  /usr/lib/libBlocksRuntime.so.0 && ldconfig` to fix it
* the `swiftc -O inference.swift` example in https://github.com/tensorflow/swift/blob/master/Usage.md won't work, it has to be explicitly given the `tensorflow` dynamic lib. like `swiftc -O inference.swift -ltensorflow`

**Comment by rxwei** [comment]
Thanks for the note! We will document this in the FAQ section as well as in `Usage.md`.
