### ISSUE TITLE
an updated pre-built package

### ISSUE THREAD

**Issue by xysun** [tensorflow/swift#104]
Hello -- can we have an updated pre-built package? Current one is of Jan 4th. 

Asking because some auto-differentiation functionality is broken in current package, but I was told the latest master works fine. See #101 

(I tried to build from source myself, but after several hours and 80+G disk space I gave up, hence the needy message =])

Thanks!

**Comment by rxwei** [comment]
We'll update toolchains today. If you'd like to keep using an updated version of Swift for TensorFlow, we would recommend [using a Colab notebook (https://github.com/tensorflow/swift/blob/master/Usage.md).

**Comment by marcrasi** [comment]
By the way, Swift in Colab is currently broken: it immediately crashes without executing any code. I'll post a workaround in 1-2 hours, and the full fix should be deployed in 2 days.

**Comment by xysun** [comment]
@tanmayb123 I'm on MacOS. I tried to build from source on a Ubuntu 16.04 though.

**Comment by marcrasi** [comment]
> Will the installation notebook work currently?

Nope, because the "latest build" that it installs is still broken on Colab. I'm currently running a build that should work in Colab -- once that finishes, the installation notebook will install a working build and that will be the workaround that I suggest.

**Comment by marcrasi** [comment]
Ok, the Colab workaround works and I have documented it at https://github.com/tensorflow/swift/blob/master/Usage.md

**Comment by xysun** [comment]
Thanks! I tried the installation notebook and confirm it works. 
I can close this issue then?
