### ISSUE TITLE
Symbols error during build with macosx Xcode latest DEVELOPMENT-2019-02-18

### ISSUE THREAD

**Issue by bobuntu** [tensorflow/swift#117]
Error building the sample code provided on [tf/swift/installation](https://github.com/tensorflow/swift/blob/master/Installation.md) and following the Xcode configuration steps provided. Here is the command:
```
Ld /Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Products/Debug/SwiftTensorflow normal x86_64
    cd /Users/.../dev.in/apps/Switml
    export MACOSX_DEPLOYMENT_TARGET=10.14
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot \
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Products/Debug \
-F/Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Products/Debug -F/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx \
-filelist /Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Intermediates.noindex/Switml.build/Debug/SwiftTensorflow.build/Objects-normal/x86_64/SwiftTensorflow.LinkFileList -Xlinker -rpath -Xlinker \
@executable_path/../Frameworks -mmacosx-version-min=10.14 -Xlinker -object_path_lto -Xlinker /Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Intermediates.noindex/Switml.build/Debug/SwiftTensorflow.build/Objects-normal/x86_64/SwiftTensorflow_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate \
-fobjc-link-runtime -L/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2019-02-18-a.xctoolchain/usr/lib/swift_static/macosx -Xlinker -force_load_swift_libs -lc++ -framework Foundation -Xlinker -add_ast_path -Xlinker \
/Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Intermediates.noindex/Switml.build/Debug/SwiftTensorflow.build/Objects-normal/x86_64/SwiftTensorflow.swiftmodule -lpython /Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/libtensorflow_framework.so \
/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/libtensorflow.so -Xlinker -dependency_info -Xlinker \
/Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Intermediates.noindex/Switml.build/Debug/SwiftTensorflow.build/Objects-normal/x86_64/SwiftTensorflow_dependency_info.dat \
-o /Users/.../Library/Developer/Xcode/DerivedData/Switml-aldlfnupfnxzsxdifjolodenjgog/Build/Products/Debug/SwiftTensorflow
```

The build fails with a 1 exit code. Full details:
```
Undefined symbols for architecture x86_64:
  "__objc_realizeClassFromSwift", referenced from:
      _swift_updateClassMetadata in libswiftCore.a(Metadata.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
>Note: Swift Playground is working fine.

**Comment by kasparlund** [comment]
same experience here when making a commandline project.
It work if you make a cocoa project

**Comment by bobuntu** [comment]
> It work if you make a cocoa project

There's 2 types of cocoa projects: Cocoa App and Cocoa Framework and neither of them is working. Using Xcode 10.1. Do you mind posting a step-by-step fix?

**Comment by kasparlund** [comment]
I do exact like the instructions for mac her: https://github.com/tensorflow/swift/blob/master/Installation.md
at first it would not work because i did not set the use of Legacy Build System. as defined in step 5
once i did that i coul create a mac cocoa app and import tensorflow + make a build

**Comment by rxwei** [comment]
Is your Xcode project created via the Swift Package Manager, or from Xcode itself? We do not formally support project creation from Xcode because Xcode is out of our control.

**Comment by bobuntu** [comment]
Hi @rxwei, I'm using Xcode itself. I'm just getting started. I'd appreciate a link to a tutorial or walkthrough using swift package manager, especially how you tell the package manager about TensorFlow toolchain.

**Comment by kasparlund** [comment]
hi bobunto: [this link](https://medium.com/@kasparlund/simple-rnn-in-swift-bc16116cda5d) might help to get startet

**Comment by johndpope** [comment]
ok - I'm seeing this too - investigating.

**Comment by johndpope** [comment]
so I did some digging - came across this article by @regularberry 
https://medium.com/livefront/how-to-add-a-dynamic-swift-framework-to-a-command-line-tool-bab6426d6c31

adding in the to user defined settings fixes above error
```shell
SWIFT_FORCE_DYNAMIC_LINK_STDLIB YES
SWIFT_FORCE_STATIC_LINK_STDLIB NO
```
seems to fix things - thanks @regularberry

**Comment by johndpope** [comment]
this file + xcodegen will spit out a suitably configured xcode project for xcode 10.1  / (10.2 not yet supported with swift-tensorflow-RELEASE-0.3.1.xctoolchain.)
https://gist.github.com/johndpope/b91748d307b2a49e710d8d0580bd52a8

**Comment by bobuntu** [comment]
Appreciate the digging @johndpope! Explicit dynamic linking could be it.
