### ISSUE TITLE
xCode 10.2 beta settings for importing TensorFlow

### ISSUE THREAD

**Issue by Theo58** [tensorflow/swift#118]
If you select "Toolchain -> Swift for TensorFlow..." in a newly installed environment of xCode 10.2 beta, you will get an error with the line "import TensorFlow". xCode can not find it. To solve this you need to set "File -> Project Settings -> Per-User Project Settings -> Build System -> legacy Build System". Now the error is gone and you can compile. You can not find this anywhere in the install documentation. May I suggest to add this to the instructions.

**Comment by rxwei** [comment]
It's there in the documentation: https://github.com/tensorflow/swift/blob/master/Installation.md#installation.
