### ISSUE TITLE
colab sample iris seems broken.

### ISSUE THREAD

**Issue by johndpope** [tensorflow/swift#120]
<img width="1101" alt="screen shot 2019-02-24 at 21 37 58" src="https://user-images.githubusercontent.com/289994/53298092-8467b500-387c-11e9-8657-5a332d8b2f17.png">

**Comment by rxwei** [comment]
See https://github.com/tensorflow/swift-tutorials/issues/9.

**Comment by johndpope** [comment]
Hi Richard, 

it would probably be ideal to proactively trap the errors spat out from google colab / swift for tensorflow - that way you could identify common errors / misuse and fire fight en masse.

and / or maybe when this / swift for tensorflow error is thrown - give option for users to click threw to a system status page - with known issue -  until things stabilize.  something to think about.
