### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by dan-zheng** [tensorflow/swift#13]
Currently, Swift is hard-coded to use Python 2.7.
Adding Python 3 support is non-trivial because the [Python.swift](https://github.com/google/swift/blob/tensorflow/stdlib/public/Python/Python.swift) standard library file calls Python C API functions specific to Python 2 (such as [`PyString_AsString`](https://github.com/google/swift/blob/tensorflow/stdlib/public/Python/Python.swift#L754)).

There are multiple possible solutions (e.g. separate `Python2`/`Python3` modules), but the best design isn't clear. Separate modules (e.g. `import Python2` and `import Python3`) is unideal because that implies not having a unified Python interface, with separate `PythonObject2` and `PythonObject3` structs for instance. On the other hand, the Python version becomes explicit and clear in the code.

An interesting solution is to offer a single `Python` module and to make Python version configurable via runtime flag, e.g. `swift --use-python3`.

This is great because Python version would be dynamic: rather than building the compiler explicitly with support for Python 2/3, users can specify the version when invoking `swift`. This also resembles the way Python scripts are run: for a single `main.py` file, users can run either `python2 main.py` or `python3 main.py`.

However, the implementation is less straightforward and runtime calls to `dlopen` may be required.

**Comment by roman-kh** [comment]
The other important thing to consider is to support [Python virtual environments](https://docs.python.org/3/tutorial/venv.html) which are widely used throughout development and production.

**Comment by johndpope** [comment]
@roman-kh  - I threw some rough notes together on Xcode to configure to a specific python conda environment   getting https://github.com/johndpope/SwiftReinforce

**Comment by eldar** [comment]
Hi there. I was wondering, given that Python 2 will cease to exist in 1 year and it is generally recommended to [stop its support in current projects](https://python3statement.org/), why is it even a question? Why would a new project like this one even aim at a dual support?

**Comment by dan-zheng** [comment]
Update: I'm a fan of the the `dlopen`/`dlsym` approach for unified Python 2/3 support presented by @pvieito in [this mailing list thread](https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/Qq92xFURBUU) and implemented in [PythonKit](https://github.com/pvieito/PythonKit).

I think it's the right approach for configurable Python support. It works with any Python installation on any platform. Python version and library path can be specified via environment variables.

With @pvieito's permission, I support merging PythonKit into the Swift Python module. Some implementation details need to be tweaked (e.g. remove dependency on Foundation for file I/O and reading environment variables). The [`PythonLibrary.getSymbol<T>(name: String, signature: T.Type) -> T`](https://github.com/pvieito/PythonKit/blob/88e259b8dff4a8259a175d3e833898bc42c9d884/PythonKit/PythonLibrary.swift#L110) idea is nice and general.

**Comment by rxwei** [comment]
See announcement: https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/Rzpgfr0XUcw

Thank you again, @pvieito and @dan-zheng!

**Comment by khushal-dugar** [comment]
If Swift supports Python 3.x now please update the readme because it can be misleading.

**Comment by KhushalDugar** [comment]
If Swift supports Python 3.x now please update the readme because it is misleading.

**Comment by dan-zheng** [comment]
> If Swift supports Python 3.x now please update the readme because it is misleading.

What section requires updating exactly?

**Comment by anandijain** [comment]
https://github.com/apple/swift/tree/tensorflow#system-requirements 
Under system requirements, there's the following:
`Please make sure you use Python 2.x. Python 3.x is not supported currently.`

**Comment by iamWing** [comment]
> https://github.com/apple/swift/tree/tensorflow#system-requirements
> Under system requirements, there's the following:
> `Please make sure you use Python 2.x. Python 3.x is not supported currently.`

As is for today the document still states that Python 3.x is not supported currently. I'm not entirely sure if we can remove this line or not, but I'm using Python 3.6 on it and it seems working just fine.
