### ISSUE TITLE
REPL not working on WSL 18.04 Ubuntu

### ISSUE THREAD

**Issue by animesh** [tensorflow/swift#142]
I have followed the following steps mentioned at https://github.com/tensorflow/swift/blob/master/Installation.md after installing the https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q in the bash prompt

> sudo apt update
> sudo apt-get install clang libpython-dev libblocksruntime-dev
> wget https://storage.googleapis.com/s4tf-kokoro-artifact-testing/latest/swift-tensorflow-DEVELOPMENT-ubuntu18.04.tar.gz
> tar xvzf swift-tensorflow-DEVELOPMENT-ubuntu18.04.tar.gz
> export PATH=$(pwd)/usr/bin:"${PATH}"

I should note that i can compile the following code using instructions from https://github.com/tensorflow/swift/blob/master/Usage.md  

````
import TensorFlow

struct MLPClassifier {
    var inpw = Tensor<Float>(shape: [2, 2], scalars: [0.15,0.25,0.20,0.3])
    var hidw = Tensor<Float>(shape: [2, 2], scalars: [0.4,0.5,0.45,0.55])
    var b1 = Tensor<Float>([0.35])
    var b2 = Tensor<Float>([0.6])

    func prediction(for x: Tensor<Float>) -> Tensor<Float> {
        let o1 = 1/(1+exp(-(matmul(x, inpw) + b1)))
        return 1/(1+exp(-(matmul(o1, hidw) + b2)))
    }
}

let inp = Tensor<Float>([[0.05,0.10]])
let classifier = MLPClassifier()
let prediction = classifier.prediction(for: inp)
print(prediction)
````
using following command
````
animeshs@DMED7596:~/Desktop/scripts$ swift -O ann_tf.swift
````
giving the desired output as mentioned at https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/  
````
[[0.75136507, 0.7729285]]
````
however when i simply type 
````
swift
````
it give no prompt/REPL and seems to hang which i have to break using ctrl-z ...

I have also tried the jupyter way, 

> sudo apt install python3-pip
> sudo pip3 install jupyter
> git clone https://github.com/google/swift-jupyter.git
> cd swift-jupyter/
> sudo pip3 install -r requirements.txt
> sudo pip3 install -r requirements_py_graphics.txt
> sudo python3 register.py --sys-prefix --swift-toolchain $HOME
> jupyter notebook

but that seems to hang hang as well as the notebook cell keeps on showing "running" symbol "*" ... any ideas what to look for in order to solve this?

**Comment by Alleno** [comment]
I'm also having the same issue, but installing just base Swift 5.01 on windows subsystem for linux.

**Comment by steph-en-m** [comment]
The does work for me upon setup but the moment I exit my terminal and reopen it; it  doesn't. I don't have a clue yet as to why the installation breaks.
Here's what i get after reopening the terminal and typing/running ```swift```
```
Command 'swift' not found, but can be installed with:

sudo snap install openstackclients     # version rocky
sudo apt  install python-swiftclient 
sudo apt  install python3-swiftclient
```

**Comment by machineko** [comment]
Any luck with solving this?

**Comment by thomfrick** [comment]
Same problem for me on WSL

**Comment by machineko** [comment]
@thomfrick Try to use WSL2 (but u wont be able to run GPU)

**Comment by moshg** [comment]
This seems not specific to S4TF.
https://bugs.swift.org/browse/SR-2700

**Comment by machineko** [comment]
Yup its problem with WSL not tensorflow i think it can be closed
