### ISSUE TITLE
[Doc] Document usage of generic constraints in '@differentiable'

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift#150]
In the [Differentiable Function and Differentiation APIs](/docs/DifferentiableFunctions.md) document, we should document the usage of generic constraints.

**Comment by dan-zheng** [comment]
The `@differentiable` declaration attribute `where` clause is [documented in the differentiable programming manifesto]( https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md#the-differentiable-declaration-attribute-1).
