### ISSUE TITLE
Error ld-2.27.so

### ISSUE THREAD

**Issue by RogerS49** [tensorflow/swift#151]
dl@DL1:~$ swift -- version
error: ld-2.27.so 0xffffffff0005c564: adding range [0x1464a-0x146ba) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0xffffffff0005c564: adding range [0x146d0-0x146d6) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0xffffffff0005c5c5: adding range [0x1464a-0x146ba) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0xffffffff0005c5c5: adding range [0x146d0-0x146d6) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
Welcome to Swift version 5.0-dev (LLVM dcb9eb74a7, Clang 95cdf7c9af, Swift 434442b530).
Type :help for assistance.

The above is the result of the first invocation of swift.
Ubuntu 18.04
Cuda 10.0
cudnn 7.5
nvidia 418.39
[ld.zip](https://github.com/tensorflow/swift/files/2978997/ld.zip)

**Comment by 313v** [comment]
i'm getting this error too

**Comment by iamWing** [comment]
Exact same error messages show on starting REPL.

```sh
wing@AI04:~$ swift
error: ld-2.27.so 0xffffffff0005c564: adding range [0x1464a-0x146ba) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0xffffffff0005c564: adding range [0x146d0-0x146d6) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0xffffffff0005c5c5: adding range [0x1464a-0x146ba) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0xffffffff0005c5c5: adding range [0x146d0-0x146d6) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
Welcome to Swift version 5.0-dev (LLVM dcb9eb74a7, Clang 95cdf7c9af, Swift 256c9fc69b).
Type :help for assistance.
```

Ubuntu 18.04
Cuda 10.0.130
Nvidia Driver 418.67

**Comment by pkese** [comment]
Apparently swift tooling fails to parse debug information from libc6-dbg, see https://bugs.swift.org/browse/SR-8690

If you're not debugging libc6, then a workaround is `sudo apt remove libc6-dbg`

**Comment by gaet2006** [comment]
I am getting the same issue. I went to the website mentioned by pkese, but the solution was to install a screenshot instead of the normal version, but I really don't want to do that. I also am not quite sure of the side effect of deleting `libc6-dbg`. Can anyone help with this? Thank you all!

**Comment by marcrasi** [comment]
Yeah, https://bugs.swift.org/browse/SR-8690 is the source of truth for this problem so I'll close this github issue.
