### ISSUE TITLE
Compile Time Error: unable to load standard library for target 'arm64-apple-ios12.0'

### ISSUE THREAD

**Issue by ardamavi** [tensorflow/swift#158]
When I'm using `Xcode 10.1` **Toolchain** for my basic `Single View iOS Application` project builded and ran successfully. But when I change **Toolchain** to `Swift for TensorFlow Release 0.2`, I get `error: unable to load standard library for target 'arm64-apple-ios12.0' ` error in compile time.

I' using:
iOS: 12.0
Swift: 4.2
Xcode: 10.1
Build System: Legacy

**Comment by rxwei** [comment]
The Swift for TensorFlow toolchain does not support iOS yet.

**Comment by ardamavi** [comment]
@rxwei Thank you.
