### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/swift#164]
I've been trying to implement some simple stuff to try out the framework (I love it) but its a bit tough not having a reference of the TensorFlow API.

**Comment by dan-zheng** [comment]
Here's the Swift for TensorFlow API reference: https://www.tensorflow.org/swift/api_docs
It is [listed on the README](https://github.com/tensorflow/swift#resources).

**Comment by cgarciae** [comment]
@dan-zheng thanks! 
I feel like an idiot, I looked for it and it was right there.

**Comment by dan-zheng** [comment]
No worries! It's definitely a dense README.
