### ISSUE TITLE
Could we add operator to Python Interoperability

### ISSUE THREAD

**Issue by frogcjn** [tensorflow/swift#171]
If we want to use the == operator to filter np array,
```Python
   idxs = np.flatnonzero(y_train == y)
```
we can do it in Swift,
```Swift
    var idxs = np.flatnonzero(y_train == y)
```
with the redefinition of equal operator
```Swift
let op = Python.import("operator")
public func == (lhs: PythonConvertible, rhs: PythonConvertible) -> PythonObject {
    return op.eq(lhs, rhs)
}
```

**Comment by lattner** [comment]
We already have == with the normal `Bool` result:

  public static func == (lhs: PythonObject, rhs: PythonObject) -> Bool {
    return lhs.compared(to: rhs, byOp: Py_EQ)
  }

Swift does support overloading on return type, but you almost never want it.  I'd recommend using a different operator for this, just use op.eq directly:

 var idxs = np.flatnonzero(op.eq(y_train, y))

or use a conversion to PythonObject:

 var idxs = np.flatnonzero(PythonObject(y_train == y))

**Comment by frogcjn** [comment]
@lattner Thanks for your reply! It is my honor to discuss the Python Interoperability of the Swift!

Another proposal is ExpressByTupleLiteral. It is mentioned several times in the Swift Evolution forum.
I found it is pretty needed for the Python Interoperability.
For example, the reshape function:
```python
X_train = X_train.reshape((X_train.shape[0], -1))
```
Currently, we must define some function or using the PythonObject.init to map the values to the Python tuple, there is no direct way to map Swift tuple to Python tuple.
```Swift
X_train = X_train.reshape(t(X_train.shape[0], -1))
```
with the defination
```
public func t<T : PythonConvertible>(_ vals: T...) -> PythonObject {
    let vals = PythonObject(vals)
    return Python.tuple(vals)
}
```

If there is an ExpressByTupleLiteral feature then it is very easy to map Swift tuple to Python tuple:
```Swift
X_train = X_train.reshape((X_train.shape[0], -1))
```
with the defination by adding ExpressibleByTupleLiteral protocol
```Swift
extension PythonObject : ExpressibleByTupleLiteral {
  public init<T: PythonConvertible>(tupleLiteral elements: PythonConvertible...) {
    let vals = PythonObject(vals)
    self = Python.tuple(vals)
  }
```

**Comment by lattner** [comment]
Definitely, I've love to see an ExpressibleByTupleLiteral feature.  Unfortunately, I suspect that that is blocked by the lack of variadic generics - it isn't important for the Python usecase, but the tuple should be allowed to have different element types in general.
