### ISSUE TITLE
[Question] Development Snapshots

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/swift#172]
Hey S4TF team.

I was wondering how often are the [development snapshots](https://github.com/tensorflow/swift/blob/master/Installation.md#development-snapshots) generated? Are they generated automatically every day? I am currently using a version where Layer defines the `applied` method without the `context` argument, but the current codebase on `master` uses `call` which is way nicer.

**Comment by saeta** [comment]
Hi @cgarciae! Great question. IIRC, they are generated every 6 hours. And as it turns out, the one available now should have the new `func call` syntax (thanks to @dan-zheng). Let me know if you encounter issues!

All the best,
-Brennan
