### ISSUE TITLE
No such module 'TensorFlow'

### ISSUE THREAD

**Issue by kikiFeng** [tensorflow/swift#18]
When my code is running in Xcode's Playground, it says "No such module 'TensorFlow'". But the result of the operation can be printed.

**Comment by rxwei** [comment]
Try restarting Xcode.

**Comment by kikiFeng** [comment]
@rxwei It works. Thank you.

**Comment by AbhimanyuAryan** [comment]
@rxwei I have Xcode Version 10.1 (10B61). I installed tensorflow for xcode(latest 2019)

but I can't seem to import TensorFlow in iOS Xcode blank playground. What am I doing wrong? I can import TensorFlow in CLI. It works

<img width="931" alt="Screenshot 2019-03-10 at 4 29 01 PM" src="https://user-images.githubusercontent.com/8083613/54084038-c5b69500-4351-11e9-8b8a-946da28acc7a.png">
<img width="790" alt="Screenshot 2019-03-10 at 4 29 59 PM" src="https://user-images.githubusercontent.com/8083613/54084039-c64f2b80-4351-11e9-9edf-e4c6942caff9.png">

**Comment by NSEGeorge** [comment]
@AbhimanyuAryan Hi! You should use macOS Playground and set build system to legacy.

**Comment by AbhimanyuAryan** [comment]
@NSEGeorge any steps to replicate that would be appreciated including screenshots. I haven't enough experience with XCode configuration & settings

**Comment by 007vasy** [comment]
https://forums.fast.ai/t/jeremys-harebrained-install-guide/43814/184 My guess is you forgot to copy the extracted binary to the right place
