### ISSUE TITLE
Tensor subscript API - TensorRange

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/swift#188]
Hey S4TF team,

I have a few questions / comments about the subscript API for the `Tensor` struct.

1. Why are we using the `TensorRangeExpression` protocol type instead of using the `TensorRange` enum type directly? I don't imagine people will actually implement another version of `TensorRangeExpression` and most importantly it makes it so the compiler cant infer e.g. `.ellipsis` from the context and makes you write `TensorRange.ellipsis` which is pretty bad for readability (which you kinda want when subscripting).
2. Why not make `stride` default to `1`? Right now you always have to type `stride: 1` which is what you want `99%` of the time.
3. Using swift ranges seems like a good idea but given you have to wrap them in specific `TensorRange` cases it defeats the purpose. Take `PartialRangeUpTo` for example, you have to type `TensorRange.PartialRangeUpTo(..<6, stride: 1)`  but having the `..<6` range gives you no benefits, its less verbose just to be able to write `TensorRange.PartialRangeUpTo(6, stride: 1)`. In this logic range's signature could be: `range(_ from: Int, _ to: Int, _ stride: Int = 1)`. It would also be better to remove `partialRangeThrough` and `closedRange`, these don't have a numpy equivalent and you easily get them by adding `+ 1`. 
4. `TensorRange.colon` or `TensorRange.all` would be a nice shortcut for `TensorRange.partialRangeFrom(0..., stride: 1)`, this is just the widely popular `:` symbol in python. 
5. Consider shortening the names:
```
partialRangeFrom -> from
partialRangeUpTo -> upTo
index -> at
```

If all of these was done you could turn this code
```swift
x[TensorRange.index(0), TensorRange.partialRangeFrom(0..., stride: 1), TensorRange.range(1..<4, stride: 1)]
```
to
```swift
x[.at(0), .from(0), .range(1, 4)]
```
which I think is the closest you could get to `x[0, :, 1:4]` for now.

**Comment by cgarciae** [comment]
Just realized there are a bunch of `TensorRangeExpression` extensions for ranges which makes this irrelevant!

**Comment by cgarciae** [comment]
One thing is that `...` is not a valid range for some reason.

**Comment by rxwei** [comment]
Yeah, this is because the unbounded range operator is actually not a nullary operator, but [a hack in the standard library](https://developer.apple.com/documentation/swift/unboundedrange-qf8). Since the operator is a function, it cannot conform to the TensorRangeExpression protocol. There are no good ways to resolve this yet, but further language improvements can definitely make this possible.
