### ISSUE TITLE
Jupyter notebook?

### ISSUE THREAD

**Issue by bokertov** [tensorflow/swift#19]
Can we try out Swift for Tensorflow in Jupyter / iPython notebooks? iPython notebook significantly boosted the popularity of Python, and could do similar thing for Swift + Tensorflow. Thanks!

**Comment by rxwei** [comment]
@rjpower made it work with Swift for TensorFlow. https://github.com/rjpower/iswift

We will be thrilled to see the community take on this project and develop a polished Jupyter + Swift solution!

**Comment by rxwei** [comment]
@algal made a dockerized Jupyter Notebook for Swift for TensorFlow:
https://github.com/algal/iSwift/tree/swift-tensorflow
