### ISSUE TITLE
Use with AMD ROCm

### ISSUE THREAD

**Issue by vegabook** [tensorflow/swift#192]
I'm successfully using [ROCm 2.4](https://www.phoronix.com/scan.php?page=news_item&px=Radeon-ROCm-2.4-Released) backend for [Tensorflow](https://rocm.github.io/tensorflow.html) on Ubunutu 19.04. Works brilliantly. But i'm not a huge fan of Python and would love to learn to use swift. Since you're using the existing C++ backend, as per your answer to a previous question about Mac compatibility, can Swift for Tensorflow also work on the ROCm version? If so, how?

**Comment by thommackey** [comment]
Have you tried it? It might very well "just work". I'd love to know if it did - not least because this could open up Mac-native GPU-enabled TF development.

**Comment by rxwei** [comment]
If you have a `libtensorflow.so` that's built with your configuration, the simplest way to try it is to substitute it for `<toolchain_dir>/usr/lib/swift/macosx/libtensorflow.so.1` in a Swift for TensorFlow toolchain.
