### ISSUE TITLE
import Tensorflow succeeds on build and run but Xcode still notifies "No such module 'TensorFlow'"

### ISSUE THREAD

**Issue by AsherYartsevTech** [tensorflow/swift#201]
We are using [JIRA](https://bugs.swift.org) instead of GitHub issues to track
our work in order to integrate more effectively with the rest of the Swift
ecosystem.

Before opening a new issue, please [search the existing
issues](https://bugs.swift.org/issues/?jql=project%20%3D%20TF) to see if your
issue has already been asked. If it's open, you can _Add Vote_ to request
the issue be prioritized. And you can start watching the issue to receive
updates.

If there are no related issues in JIRA, please file a new ticket by using one
of the links below corresponding to the nature of your issue:

  - [Create a bug](https://bugs.swift.org/secure/CreateIssue.jspa?issuetype=10006&pid=10100)
  - [Create a new feature request (Story)](https://bugs.swift.org/secure/CreateIssue.jspa?issuetype=10001&pid=10100)
  - [Create a new clean up / internal improvement](https://bugs.swift.org/secure/CreateIssue.jspa?issuetype=10003&pid=10100)

**Comment by brettkoonce** [comment]
see also https://bugs.swift.org/browse/TF-573

**Comment by brettkoonce** [comment]
see also #202

**Comment by AsherYartsevTech** [comment]
Great!
