### ISSUE TITLE
[macOS] only the 'development' toolchain succeeds to build&run

### ISSUE THREAD

**Issue by AsherYartsevTech** [tensorflow/swift#202]
https://bugs.swift.org/browse/TF-573

**Comment by brettkoonce** [comment]
see also https://bugs.swift.org/browse/TF-573

**Comment by dan-zheng** [comment]
This linker issue was fixed in https://github.com/apple/swift/pull/25328.
A new macOS toolchain is being built now. I'll reply with a link to the new toolchain soon.

**Comment by dan-zheng** [comment]
New [June 12, 2019 Xcode toolchain](https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2019-06-12-a-osx.pkg) posted under [Development Snapshots](https://github.com/tensorflow/swift/blob/master/Installation.md#development-snapshots).

Please note that we're experiencing code signing issue, so you will likely encounter:
![image](https://user-images.githubusercontent.com/5590046/59396852-60eb4c00-8d3f-11e9-9487-faee9a98e153.png)
To install the toolchain, go to `System Preferences > Security & Privacy > Open Anyway`.

**Comment by AsherYartsevTech** [comment]
@dan-zheng 
I appreciate your fast response and care! it works great now and I can FINALLY jump to definitions!
