### ISSUE TITLE
June 13 Xcode installer is not signed with Developer ID

### ISSUE THREAD

**Issue by dave-fernandes** [tensorflow/swift#204]
The installer won't run on macOS 10.14.5.

**Comment by Ayush517** [comment]
Try going to Settings > Security & Privacy
There you might find the option to "Run Anyway"

Let me know if that helps :)

**Comment by dan-zheng** [comment]
Yes, we're experiencing code signing issues on macOS, so `System Preferences > Security & Privacy > Open Anyway` will be necessary for a while. Sorry for the inconvenience!

**Comment by dave-fernandes** [comment]
Yes, that works.
