### ISSUE TITLE
The active toolchain is not compatible with playgrounds. PlaygroundLogger.framework could not be loaded.

### ISSUE THREAD

**Issue by farazBhatti** [tensorflow/swift#206]
macos 10.14
xcode 10.2.1
macos chosen for Playground
toolchain : swift for TensorFlow Developement Snapshot 6/12/19

get this error when ever trying to import TensorFlow.

**Comment by zhao15** [comment]
same issue.

**Comment by badlogicmanpreet** [comment]
I am facing the same issue.

**Comment by mauceri** [comment]
I have the same issue on macos 10.14.4 and xcode 11.0 beta 3.

**Comment by mojinfu** [comment]
I am facing the same issue.

**Comment by badlogicmanpreet** [comment]
@mojinfu @mauceri You can try by creating a macOS console project (within XCode), it works there. Somehow not on the playground.

For s4tf - Is there a way to update the toolchain, the way it's done on the collab for ubuntu?

**Comment by rxwei** [comment]
The Swift for TensorFlow project does not officially support Xcode Playgrounds. While the core team is not maintaining Playgrounds support, we would gladly welcome any open source contributions that build towards a fix.

[TF-500](https://bugs.swift.org/browse/TF-500) is keeping track of all known issues related to Xcode Playgrounds. If you find other issues, feel free to add them there directly.

**Comment by mauceri** [comment]
Hi Richard, you were just saying the contrary in this video : https://www.youtube.com/watch?v=3fJsqGHhlVA&t=176s <https://www.youtube.com/watch?v=3fJsqGHhlVA&t=176s> :) But I understand you have other priorities.
