### ISSUE TITLE
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.14.sdk'

### ISSUE THREAD

**Issue by KawashimaHirotaka** [tensorflow/swift#208]
- Toolchain v0.4.0
- macOS 10.14.5
- Xcode 10.2.1
---

After passing through the path, when I launched `swift` on Terminal, I got ``` <unknown>: 0: error: Swift does not support the SDK 'MacOSX 10.14 .sdk'. ```

Do I need macOS 10.15 beta or Xcode 11, by any chance?

**Comment by rxwei** [comment]
Try the following
```
export SDKROOT=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
```

If it does work, you can add it to your `~/.bash_profile` or `~/.zshrc`.

**Comment by mikowals** [comment]
I fixed this error by:

1. Install the Xcode 11 beta from https://developer.apple.com/download/
2. Make sure the app Xcode-beta is in your Applications folder (I had to move it from downloads)
3. run `sudo xcode-select -s /Applications/Xcode-beta.app` from the command line.

I had also set SDKROOT as mentioned above but without step 3 above this did not resolve the error.

**Comment by KawashimaHirotaka** [comment]
> I fixed this error by:
> 
> 1. Install the Xcode 11 beta from https://developer.apple.com/download/
> 2. Make sure the app Xcode-beta is in your Applications folder (I had to move it from downloads)
> 3. run `sudo xcode-select -s /Applications/Xcode-beta.app` from the command line.
> 
> I had also set SDKROOT as mentioned above but without step 3 above this did not resolve the error.

It was solved after you put your solution into practice! THANK YOU!!

**Comment by bendecoste** [comment]
If you don't want to download the Xcode beta and wish to continue using Xcode 10, you can solve this by 

```
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/
```

**Comment by awav** [comment]
@bendecoste , I have Xcode 10.3, and your solution doesn't work for me :(, other suggestions what can be done?
