### ISSUE TITLE
failed to launch REPL process: process exited with status -1 (Error 1)

### ISSUE THREAD

**Issue by zhao15** [tensorflow/swift#212]
I got issue as following:

$ swift
error: failed to launch REPL process: process exited with status -1 (Error 1)
$ swift -version
Apple Swift version 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14)
Target: x86_64-apple-darwin19.0.0

**Comment by dan-zheng** [comment]
Hi @zhao15,

Based on the output for `swift -version`, it seems `swift` isn't using a Swift for TensorFlow toolchain. Could you follow [these instructions](https://github.com/tensorflow/swift/blob/master/Installation.md#using-downloads) to ensure that the Swift for TensorFlow toolchain is in your `$PATH`?

**Comment by zhao15** [comment]
That worked, thanks @dan-zheng .
