### ISSUE TITLE
Google-signed toolchains do not work with macOS Catalina.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift#222]
<img width="488" alt="Screen Shot 2019-07-29 at 3 48 50 PM" src="https://user-images.githubusercontent.com/856507/62053666-5e25b700-b218-11e9-9724-b942f4801f6e.png">

We should fix this soon.

**Comment by SamuraiJack76** [comment]
<img width="725" alt="Bildschirmfoto 2019-07-29 um 20 03 36" src="https://user-images.githubusercontent.com/13968660/62071056-000acb00-b23c-11e9-919a-c967f7f4fd70.png">
Agree!

**Comment by dan-zheng** [comment]
We are investigating a robust way to codesign toolchains that work with macOS Catalina.

In the meantime, the [Xcode 11 beta v0.4rc4 toolchain](https://storage.googleapis.com/swift-tensorflow-artifacts/releases/v0.4/rc4/swift-tensorflow-RELEASE-0.4-osx.pkg) has been replaced with a locally signed toolchain. After clicking on the toolchain, you will need to do `System Preferences` > `Security & Privacy` > `General` > `Open anyway` to open it.

If someone could verify that this works, that would be appreciated!

**Comment by 8bitmp3** [comment]
@dan-zheng @rxwei just saw this issue and tested on my XCode 10.2.1. Unfortunately, `Check and Install Now` does not install July 29's 0.4 RC4 toolchain and even with `Legacy Build System` enabled running a simple example returns a toolchain `not compatible` error 🤔

<img width="958" alt="image" src="https://user-images.githubusercontent.com/19637339/62076334-575e6a80-b23f-11e9-994b-a66491d14e78.png">

**Comment by 8bitmp3** [comment]
hey @dan-zheng, just wanted to let you know, I tried the "10-08" dev toolchain and it causes XCode 10.2.1 to crash/quit unexpectedly. Using MacOS Mojave.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/19637339/62836183-7bb34180-bc58-11e9-97c1-410f523becbe.png">

**Comment by dan-zheng** [comment]
> hey @dan-zheng, just wanted to let you know, I tried the "10-08" dev toolchain and it causes XCode 10.2.1 to crash/quit unexpectedly. Using MacOS Mojave.
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/19637339/62836183-7bb34180-bc58-11e9-97c1-410f523becbe.png">

Could you please share more context?
* What triggers the Xcode crash exactly? (e.g. merely selecting the 10/08 toolchain, or using it to build, or sth else)
* How can others reproduce this crash?

**Comment by 8bitmp3** [comment]
> Could you please share more context?
> 
> * What triggers the Xcode crash exactly? (e.g. merely selecting the 10/08 toolchain, or using it to build, or sth else)

Hey @dan-zheng Just saw your message. Selecting the latest toolchain keeps triggering the crash unfortunately. I'm reinstalling it, along with the 25 July and 17 June ones to see if the behavior is my Xcode specific

**Comment by 8bitmp3** [comment]
Ok @dan-zheng this seems connected: https://github.com/tensorflow/swift/issues/206 and https://stackoverflow.com/questions/50081481/can-not-import-tensorflow-for-swift-in-xcode-playground?rq=1
Unfortunately, still doesn't work with MacOS playgrounds and the latest August toolchain crashes XCode on my machine

**Comment by 8bitmp3** [comment]
The Sep 19 v0.5-rc1 toolchain works with Xcode 11 GM Seed
Well done @rxwei, @dan-zheng and S4TF team.

@rxwei you should close this issue.

**Comment by rxwei** [comment]
Thanks for verifying. Could you verify whether it works with Xcode 11 GM Seed on **macOS Catalina**?

**Comment by 8bitmp3** [comment]
> Thanks for verifying. Could you verify whether it works with Xcode 11 GM Seed on **macOS Catalina**?

On it @rxwei

**Comment by 8bitmp3** [comment]
> > Thanks for verifying. Could you verify whether it works with Xcode 11 GM Seed on **macOS Catalina**?
> 
> On it @rxwei

Verified @rxwei @dan-zheng . Training a small conv net now on the CIFAR-10 in Xcode 11 GM seed using the Sep 19 v0.5-rc1 toolchain - on a fresh version of macOS Catalina 10.15 beta 8 (19A558d)- all beta 👍

<img width="861" alt="image" src="https://user-images.githubusercontent.com/19637339/65375426-70a6f480-dc8d-11e9-9328-724ca3bdf5e3.png">

<img width="198" alt="image" src="https://user-images.githubusercontent.com/19637339/65375429-7b618980-dc8d-11e9-813e-063ec5922cb7.png">

<img width="268" alt="image" src="https://user-images.githubusercontent.com/19637339/65375441-c7acc980-dc8d-11e9-9668-4f6bf93699cd.png">

**Comment by rxwei** [comment]
Thank you, @8bitmp3!

**Comment by rxwei** [comment]
No more concerns with code signing for releases. cc @ematejska @bgogul
