### ISSUE TITLE
The active toolchain is not compatible with playgrounds. libswiftCore.dylib could not be loaded.

### ISSUE THREAD

**Issue by lumialxk** [tensorflow/swift#23]
Following the Installation.md. I got this error.

> The active toolchain is not compatible with playgrounds. libswiftCore.dylib could not be loaded.  

I'm using  Xcode 9.3.

**Comment by dan-zheng** [comment]
It's likely you created an iOS playground, not a macOS playground. Currently only macOS playgrounds are supported.
Could you please check?

**Comment by lumialxk** [comment]
@dan-zheng Thanks! it works.

**Comment by dan-zheng** [comment]
Great!
