### ISSUE TITLE
How to save trained model in Swift for TensorFlow?

### ISSUE THREAD

**Issue by aktrader2000** [tensorflow/swift#240]
This tutorial https://colab.research.google.com/github/tensorflow/swift/blob/master/docs/site/tutorials/model_training_walkthrough.ipynb#scrollTo=LDrzLFXE8T1l contains every step of TensorFlow walkthrough in Swift, except for saving the model. Can I save trained model to .pb file using Swift?

**Comment by rxwei** [comment]
Unfortunately, we have not yet developed standard APIs to save a model. This remains in our roadmap.

Related discussions: [[1]](https://groups.google.com/a/tensorflow.org/forum/#!msg/swift/zaxfmhZmX-8/aorgIgrNAgAJ) [[2]](https://github.com/tensorflow/swift-apis/issues/25)

**Comment by 8bitmp3** [comment]
@rxwei I think this is from your team's slides. can't wait for SavedModels and, hopefully, being able to make those models work with CoreML Tools

<img width="916" alt="image" src="https://user-images.githubusercontent.com/19637339/65057196-28749300-d96a-11e9-9c6f-6934e5cd412e.png">

**Comment by dan-zheng** [comment]
Unfortunately, we don't have a full story for importing pre-trained models yet.

Related TensorFlow checkpoint reader: https://github.com/tensorflow/swift-apis/pull/529
