### ISSUE TITLE
Toolchain isn't compatible with playgrounds

### ISSUE THREAD

**Issue by hisavali** [tensorflow/swift#25]
Hi,

I installed pre-built package for Xcode as per info here: https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages

Has anyone faced the issue highlighted in 👇:

<img width="1108" alt="screen shot 2018-05-14 at 23 23 40" src="https://user-images.githubusercontent.com/2108707/40026707-5a221d10-57ce-11e8-9edf-b30f27dbd8f0.png">

Please note I'm using Xcode9.2.

**Comment by rxwei** [comment]
Try restarting Xcode.

**Comment by kfchyc** [comment]
you should notice that the swift for tensorflow is suitable only in Mac playground. you can check your playground whether that is for macOS.

**Comment by hisavali** [comment]
Playground for macOS does the trick. Thanks @kfchyc. 👍
