### ISSUE TITLE
install swift for tensorflow?

### ISSUE THREAD

**Issue by zhanyongzhe** [tensorflow/swift#274]
Xcode : 10.3
Swift version 5.0.1

import Tensorflow
error: repl.swift:2:8: error: no such module 'Tensorflow'

**Comment by 8bitmp3** [comment]
@zhanyongzhe You are using Xcode 10, try installing with Xcode 11 Beta via https://developer.apple.com/download/ - you may need to set up an account with Apple.

As per https://github.com/tensorflow/swift/blob/master/Installation.md :
<img width="521" alt="image" src="https://user-images.githubusercontent.com/19637339/64885378-ef7faa00-d65b-11e9-92d0-b93bc84fa748.png">

@rxwei Let us know pls if you have tested it on Xcode 11 GM Seed (September 10, 2019) - can't wait for 0.5 👏

<img width="804" alt="image" src="https://user-images.githubusercontent.com/19637339/64885493-38cff980-d65c-11e9-9101-761f156bd082.png">

**Comment by zhanyongzhe** [comment]
> You'll need to switch to the legacy build system. See [Installation instructions](https://github.com/tensorflow/swift/blob/master/Installation.md#installation).



> 您需要切换到旧版构建系统。请参阅[安装说明](https://github.com/tensorflow/swift/blob/master/Installation.md#installation)。

thank ! 
March 23, 2019  version
install swift in tensorflow success!

**Comment by zhanyongzhe** [comment]
> @zhanyongzhe您正在使用Xcode 10，尝试通过https://developer.apple.com/download/安装Xcode 11 Beta - 您可能需要在Apple上设置一个帐户。
> 
> 根据https://github.com/tensorflow/swift/blob/master/Installation.md：
> <img alt="图片" width="521" src="https://user-images.githubusercontent.com/19637339/64885378-ef7faa00-d65b-11e9-92d0-b93bc84fa748.png">
> 
> @rxwei如果您在Xcode 11 GM Seed（2019年9月10日）上测试过，请告诉我们 - 不能等到0.5👏
> 
> <img alt="图片" width="804" src="https://user-images.githubusercontent.com/19637339/64885493-38cff980-d65c-11e9-9101-761f156bd082.png">

thank ！

**Comment by 8bitmp3** [comment]
@zhanyongzhe The Sep 19th v0.5-rc1 toolchain works with Xcode 11 GM Seed - try it out. As usual, follow the instructions here: https://github.com/tensorflow/swift/blob/master/Installation.md
Well done @rxwei and team 👍 

<img width="527" alt="image" src="https://user-images.githubusercontent.com/19637339/65346108-d636aa80-dbd3-11e9-9830-e5eb7842a232.png">
