### ISSUE TITLE
Foundations functions are not marked as '@differentiable'

### ISSUE THREAD

**Issue by pedronahum** [tensorflow/swift#288]
Hi,

It seems that several functions from Foundations have not been marked as '@differentiable', such as pow, sqrt, and erf.

This creates a problem if you leverage these functions inside your code and you would like to calculate gradients. 
 
Thanks,

Pedro N.

**Comment by rxwei** [comment]
Only a small subset of libc math functions are currently marked as `@differentiable`. They are defined [here](https://github.com/apple/swift/blob/tensorflow/stdlib/public/Platform/tgmath.swift.gyb). To make more be differentiable, we need to define custom derivatives for them. If you are interested, feel free to take it on!

We use JIRA to track all toolchain-level issues, so I opened [TF-812](https://bugs.swift.org/browse/TF-812) and will close this one.
