### ISSUE TITLE
error: cannot call value of non-function type 'PythonObject'

### ISSUE THREAD

**Issue by Honghe** [tensorflow/swift#29]
Environment:
```
swift --version
Swift version 4.2-dev (LLVM 04bdb56f3d, Clang b44dbbdf44, Swift aa19e11af7)
```

Source:
```
import Python
let np = Python.import("numpy")
print(np)
print(np.arange)
let a = np.arange(15).reshape(3, 5)
let b = np.array([6, 7, 8])
```
Output:
```
<module 'numpy' from '/usr/lib/python2.7/dist-packages/numpy/__init__.pyc'>
<built-in function arange>

error: cannot call value of non-function type 'PythonObject'
let a = np.arange(15).reshape(3, 5)
        ~~~~~~~~~^
error: cannot call value of non-function type 'PythonObject'
let b = np.array([6, 7, 8])
        ~~~~~~~~^
```

**Comment by dan-zheng** [comment]
This is because [`@dynamicCallable`](https://gist.github.com/lattner/a6257f425f55fe39fd6ac7a2354d693d) is not yet implemented.

Until then, you'll need to write `.call(with:)` explicitly:
`np.arange.call(with: 15).reshape.call(with: 3, 5)`

@dynamicCallable is currently being implemented and should be pushed within a week! I'll update here when it's pushed.

**Comment by Honghe** [comment]
Got it, Thanks!

**Comment by dan-zheng** [comment]
[`@dynamicCallable`](https://gist.github.com/lattner/a6257f425f55fe39fd6ac7a2354d693d) is done as of https://github.com/apple/swift/commit/214207549dde34bb9f98b0c7b0db38437c3068c7 and has been added to `PythonObject`.
You can now run the following:

```console
$ swift
Welcome to Swift version 4.2-dev (LLVM 04bdb56f3d, Clang b44dbbdf44, Swift 70260a59ef). Type :help for assistance.
  1> import Python
  2. let np = Python.import("numpy")
np: Python.PythonObject = <module 'numpy' from '/Users/danielzheng/Library/Python/2.7/lib/python/site-packages/numpy/__init__.pyc'>
  3> let a = np.arange(15).reshape(3, 5)
a: Python.PythonObject =
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
  4> let b = np.array([6, 7, 8])
b: Python.PythonObject = [6 7 8]
```

Please download the [latest Swift for TensorFlow packages](https://github.com/tensorflow/swift/blob/master/Installation.md) to try it out!
