### ISSUE TITLE
Release .tar.gz contains 4 duplicates of libtensorflow.so

### ISSUE THREAD

**Issue by kazimuth** [tensorflow/swift#293]
I downloaded `swift-tensorflow-RELEASE-0.5-cuda10.0-cudnn7-ubuntu18.04.tar.gz` and am working on setting up a docker image. I noticed that it contains 4 duplicates of libtensorflow.so:
```
usr/lib/lldb/swift/linux/libtensorflow.so
usr/lib/lldb/swift/linux/libtensorflow.so.1
usr/lib/lldb/swift/linux/libtensorflow.so.1.14.0
usr/lib/swift/linux/libtensorflow.so.1.14.0 to
```
these are bit-identical files, they add 1.5 gigs to the download and could be replaced with symlinks.

**Comment by dan-zheng** [comment]
Thanks for reporting! We're investigating this as a medium-priority issue, this [mailing list thread](https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/aw1wFSp9i7M) has more discussion.

**Comment by BradLarson** [comment]
I believe this issue was fixed a while ago, so I think we can safely close this out.
