### ISSUE TITLE
"Missing argument" error got when reading `Usage.md`

### ISSUE THREAD

**Issue by Evian-Zhang** [tensorflow/swift#299]
My swift version is:
```
Swift version 5.1-dev (LLVM 200186e28b, Swift 1238976565)
Target: x86_64-apple-darwin19.0.0
```
I am following the steps described in [Using Swift for TensorFlow](https://github.com/tensorflow/swift/blob/master/Usage.md). But get the following error:
```swift
  1> import TensorFlow
  2> var x = Tensor<Float>([1, 2], [3, 4])
error: repl.swift:2:22: error: missing argument labels 'shape:scalars:' in call
var x = Tensor<Float>([1, 2], [3, 4])
                     ^
                      shape:  scalars:
```
Maybe the tutorial should be updated?

**Comment by rxwei** [comment]
You missed a pair of square brackets. The tutorial says:
```console
2> var x = Tensor<Float>([[1, 2], [3, 4]])
```
The argument is `[[1, 2], [3, 4]]`, not `[1, 2], [3, 4]`.
