### ISSUE TITLE
numpy broadcast NotImplemented in Swift 4.2

### ISSUE THREAD

**Issue by Honghe** [tensorflow/swift#30]
Environment:
```
Ubuntu 16.04
swift --version
Swift version 4.2-dev (LLVM 04bdb56f3d, Clang b44dbbdf44, Swift aa19e11af7)
```

Source:
```
import Python
let np = Python.import("numpy")
let a = np.arange.call(with: 15).reshape.call(with: 3, 5)
print(a)

let c = 2 * a
print(c)
```
Output:
```
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
NotImplemented
```

**Comment by dan-zheng** [comment]
This is due to order of operations.
`2 * a` internally calls `2. __mul__(a)`, which yields `NotImplemented` error.
`a * 2` however is fine:

```
  6> a * 2
$R0: Python.PythonObject =
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
```

`2 * a` works fine in Python however. I wonder how it gets resolved.

**Comment by chenruisilalala** [comment]
but how to update swift for tensor flow  in Xcode ?

**Comment by dan-zheng** [comment]
@chenruisilalala 
To use Swift for TensorFlow in Xcode, please [install an Xcode toolchain](https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages) then [follow these instructions](https://github.com/tensorflow/swift/blob/master/Usage.md#mac-only-xcode).

If that didn't answer your question, please rephrase it and create a new issue.

**Comment by fkm3** [comment]
I don't think this should have been closed.

In python this resolves to `__rmul__` instead of `__mul__`:
https://docs.python.org/3/reference/datamodel.html#object.__rmul__

Maybe the swift python interop isn't handling the `__r*__` variants?

**Comment by dan-zheng** [comment]
Aha, that makes sense.
I'll look into supporting `__r*__` operations.

**Comment by dan-zheng** [comment]
This is fixed in https://github.com/apple/swift/commit/70260a59ef4c6b27507a8168c2786a83a32cc373.
In your example above, both `2 + a` and `a + 2` now work.

---

By the way, [`@dynamicCallable`](https://gist.github.com/lattner/a6257f425f55fe39fd6ac7a2354d693d) is also done as of https://github.com/apple/swift/commit/214207549dde34bb9f98b0c7b0db38437c3068c7 and has been added to `PythonObject`.
You can now run the following:

```console
$ swift
Welcome to Swift version 4.2-dev (LLVM 04bdb56f3d, Clang b44dbbdf44, Swift 70260a59ef). Type :help for assistance.
  1> import Python
  2> let np = Python.import("numpy")
np: Python.PythonObject = <module 'numpy' from '/Users/danielzheng/Library/Python/2.7/lib/python/site-packages/numpy/__init__.pyc'>
  3> let a = np.ones([2, 3])
a: Python.PythonObject =
[[1. 1. 1.]
 [1. 1. 1.]]
  4> 2 + a
$R0: Python.PythonObject =
[[3. 3. 3.]
 [3. 3. 3.]]
  5> a + 2
$R1: Python.PythonObject =
[[3. 3. 3.]
 [3. 3. 3.]]
```

Please download the [latest Swift for TensorFlow packages](https://github.com/tensorflow/swift/blob/master/Installation.md) to try it out!

**Comment by lattner** [comment]
Nice, did you add a testcase for this bug report?

**Comment by dan-zheng** [comment]
Unfortunately, I didn't because I don't know how to test this in pure Python without importing NumPy and without the ability to easily create custom classes.

I can look into adding a lit config "numpy" available feature for running NumPy-specific tests.
