### ISSUE TITLE
Cannot load module 'TensorFlow' as 'Tensorflow' in xcode 11.1

### ISSUE THREAD

**Issue by nilday** [tensorflow/swift#310]
Hi everyone 
I follow the lead of https://github.com/tensorflow/swift/blob/master/Installation.md try to install swift for tensorflow.
I switch to swift for tensorflow toolchain and change to legacy build system, but it still doesn't work for me.
Can anyone offer some help? Thank you very much
![image](https://user-images.githubusercontent.com/3797285/67377906-f681cc80-f5b8-11e9-919e-aa1010d5fbb4.png)

![image](https://user-images.githubusercontent.com/3797285/67377847-e10ca280-f5b8-11e9-966f-692100f1a3be.png)

![image](https://user-images.githubusercontent.com/3797285/67377622-8a9f6400-f5b8-11e9-8f1e-cd67efa04f43.png)

**Comment by dan-zheng** [comment]
Please try `import TensorFlow` instead of `import Tensorflow`.

**Comment by nilday** [comment]
> Please try `import TensorFlow` instead of `import Tensorflow`.

Ohhh~  Who silly of me! Thank you !
