### ISSUE TITLE
How can I find the latest package release.

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [tensorflow/swift#32]
I am a novice.
How can I find the latest package release.
Thank you give me a address.

**Comment by kfchyc** [comment]
readme.md

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhuiyizhiqiu** [comment]
@kfchyc  Outlook for iOS have not +86 for Chain

**Comment by kfchyc** [comment]
That’s a signature by my mail app automatically. I mean that you can find the newest version in the README.md file. There is a link.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhuiyizhiqiu** [comment]
@kfchyc  I know your mean. I have read  the README.md. Then I also read Install Swift for TensorFlow. But the file section of Installation have the "1 Download the latest package release". I can not find the package release.

**Comment by kfchyc** [comment]
The “Download the latest package release “ is a hyperlink with blue text color. You should click it.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhuiyizhiqiu** [comment]
@kfchyc  <img width="857" alt="2018-05-28 4 10 19" src="https://user-images.githubusercontent.com/16648917/40604467-af71f2a4-6291-11e8-9f8a-2ac9e835ff50.png">
The "Download the latest package release " is not a hyperlink with blue text color. I Can not click it.

**Comment by kfchyc** [comment]
[Image][Image]

But it looks like this in my safari.
________________________________

**Comment by zhuiyizhiqiu** [comment]
@kfchyc  Can you gave me the hyperlink? Your image I can not download.

**Comment by kfchyc** [comment]
https://github.com/tensorflow/swift/blob/master/Installation.md

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhuiyizhiqiu** [comment]
@kfchyc  God, I still can't. Why does it look like this

**Comment by kfchyc** [comment]
Xcode：
https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2018-05-10-a-osx.pkg
Ubuntu1604:
https://storage.googleapis.com/swift-tensorflow/ubuntu16.04/swift-tensorflow-DEVELOPMENT-2018-05-10-a-ubuntu16.04.tar.gz
Ubuntu1404:
https://storage.googleapis.com/swift-tensorflow/ubuntu14.04/swift-tensorflow-DEVELOPMENT-2018-05-10-a-ubuntu14.04.tar.gz

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dan-zheng** [comment]
Thanks for posting direct links @kfchyc.
@zhuiyizhiqiu, are you able to use those links directly?

**Comment by zhuiyizhiqiu** [comment]
@dan-zheng ok,I am loading the package.

**Comment by zhuiyizhiqiu** [comment]
@kfchyc  Thank you very much.

**Comment by zhuiyizhiqiu** [comment]
@dan-zheng  I hope the download the link add in the readme.md.
