### ISSUE TITLE
Playground execution failed

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [tensorflow/swift#33]
<img width="959" alt="2018-05-29 10 17 21" src="https://user-images.githubusercontent.com/16648917/40634816-913b0512-6329-11e8-9580-b838fa2bacd2.png">
I execution the code success in the first. But I execution the code in the second, than the bug is show.

**Comment by dan-zheng** [comment]
Playgrounds is known to occasionally hang or crash.
Could you try restarting Xcode or creating a new Playground?

**Comment by zhuiyizhiqiu** [comment]
I have try restarting Xcode more and more time. But the bug is continued. Though, I can’t resolve the bug to creat a new Plaground

**Comment by dan-zheng** [comment]
Are you able to run the code in your Playgrounds via the Swift REPL/interpreter/compiler successfully?

The error log shows `eExpressionSetupError` which indicates Playgrounds is frozen and restarting Xcode is necessary. For the record, I am able to run the Playground successfully:
![screen shot 2018-05-29 at 9 53 46 am](https://user-images.githubusercontent.com/5590046/40673437-ab23c7aa-6326-11e8-8aac-59319024aebb.png)

If you encounter many problems with Playgrounds, I'd recommend using the Swift interpreter instead to run your code via the command line.

**Comment by zhuiyizhiqiu** [comment]
<img width="573" alt="2018-05-30 11 28 18" src="https://user-images.githubusercontent.com/16648917/40697396-96fc7214-63fc-11e8-893a-958407305cbd.png">
My version is swift 4.1. The Swift For TensorFlow must have swift 4.2 ?

**Comment by kfchyc** [comment]
4.2 is a beta version.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rxwei** [comment]
You seem to be running Swift 4.1 release in the terminal. Swift for TensorFlow is located in the toolchain installation path. You can use [swiftenv](https://swiftenv.fuller.li/en/latest/installation.html#via-homebrew) to manage your toolchains more easily.

**Comment by zhuiyizhiqiu** [comment]
Swift for TensorFlow can be running with Swift 4.1?

**Comment by zhuiyizhiqiu** [comment]
<img width="573" alt="2018-05-30 8 16 33" src="https://user-images.githubusercontent.com/16648917/40719505-6415737e-6446-11e8-9162-2198e2c058cb.png">
That is not work!

**Comment by zhuiyizhiqiu** [comment]
<img width="570" alt="2018-05-30 8 26 45" src="https://user-images.githubusercontent.com/16648917/40719978-d3cf8f3c-6447-11e8-92e4-d931102102dd.png">
Ok! Thank your effort .
I am successful !

**Comment by jungwook8580** [comment]
Hi! I need help! Have you seen this error before?


![image](https://user-images.githubusercontent.com/29832066/46925148-5fa93880-d065-11e8-8e56-6914f121ae61.png)

**Comment by zhuiyizhiqiu** [comment]
Can you have installed the xcode10?

**Comment by jungwook8580** [comment]
downgraded to xcode9 since version 10 keeps exciting itself everytime i type 'shift + {'
