### ISSUE TITLE
Tensor Random Normal

### ISSUE THREAD

**Issue by rakesh4real** [tensorflow/swift#334]
[EXPLICIT PARAMETER TYPE DECLARATION]

```
let noise = ( Tensor<Float>(randomNormal: [100], mean: Tensor<Float>(5.0) , standardDeviation: Tensor<Float>(10.0), seed: TensorFlowSeed(graph: 7, op: 7)) ) * 5
```
This is not a big issue (or an issue if you may say so), but note that we have to provide explicit data type for parameters `mean` and `standardDeviation` even though ` Tensor<Float>` was declared right in the begining; Otherwise error occurs. Generics can be implemented here.

**Comment by dan-zheng** [comment]
Hi @rakesh4real,

Specifying `Tensor<Float>` only once seems to work fine for me, with [latest development toolchains](https://github.com/tensorflow/swift/blob/master/Installation.md#development-snapshots):
```swift
import TensorFlow
let noise = Tensor<Float>(
    randomNormal: [100],
    mean: Tensor(5.0),
    standardDeviation: Tensor(10.0),
    seed: TensorFlowSeed(graph: 7, op: 7)) * 5
```

Could you please confirm whether this works for you?

**Comment by rakesh4real** [comment]
Hi,
It works amazingly fine.
Thanks,
Rakesh
