### ISSUE TITLE
TensorFlow doesn't work in REPL, Playground and macOS App

### ISSUE THREAD

**Issue by SpectralDragon** [tensorflow/swift#34]
Hello! I have problem. I setup latest `swift-tensorflow-DEVELOPMENT-2018-05-10-a.xctoolchain`, used `export PATH=/Library/Developer/Toolchains/swift-latest/usr/bin:"${PATH}"` and select on 'Swift for TensorFlow Development Snapshot' and nothing.

My macOS Playground don't compile:
![image](https://user-images.githubusercontent.com/6003467/40671685-42842d80-6375-11e8-98ec-6b8844f1ecfd.png)

MacOS Cocoa App has crashes:
![image](https://user-images.githubusercontent.com/6003467/40671484-ac27a8c6-6374-11e8-99be-8a5716e01f2b.png)

And REPL can't find `TensorFlow Module`:
![image](https://user-images.githubusercontent.com/6003467/40671523-c9fcaad6-6374-11e8-8220-b3e1e76a9967.png)

That my toolchains:
![image](https://user-images.githubusercontent.com/6003467/40671563-e3b6a526-6374-11e8-9727-21fd3c14652d.png)

And `env`:
![image](https://user-images.githubusercontent.com/6003467/40671744-6bbe04f0-6375-11e8-8d5d-34a19f1c0d34.png)

What I do wrong? Except programming, of course..

**Comment by dan-zheng** [comment]
1. macOS playgrounds are known to hang, sometimes with the `eSetupExpressionError` error. Could you please try restarting Xcode or creating a new Playground?
2. Could you please share the code for your Cocoa app? More information is needed to debug. I created a new Cocoa app, imported the TensorFlow module, and ran the app successfully:
![screen shot 2018-05-29 at 9 32 49 am](https://user-images.githubusercontent.com/5590046/40672813-c052ff76-6324-11e8-8684-1712e44e844a.png)
3. It seems that you're using a different version of the Swift REPL. To use the Swift for TensorFlow toolchain with command-line tools, add the toolchain to your path as follows:
```
$ export PATH=/Library/Developer/Toolchains/swift-latest/usr/bin:"${PATH}"
```

Alternatively, you can install [`swiftenv`](https://swiftenv.fuller.li/) and run the following:
```
swiftenv global tensorflow-DEVELOPMENT-2018-05-10-a
```

**Comment by SpectralDragon** [comment]
@dan-zheng swiftenv helped me and REPL does work fine, but my macOS App and Playground don't compile... I create new macOS app and set your example below, but my compile get error: 
![image](https://user-images.githubusercontent.com/6003467/40676053-37bd0dd8-6382-11e8-9d6a-a2469839c2e6.png)

And my playground has infinite running, I don't know why..
![image](https://user-images.githubusercontent.com/6003467/40676128-773cc714-6382-11e8-91b4-71183e9e3de6.png)

REPL:
![image](https://user-images.githubusercontent.com/6003467/40676175-a51fd7f2-6382-11e8-9e96-32696243ad0a.png)

**Comment by SpectralDragon** [comment]
Deleting ‘DerivedData’ did not help me with problem. I’m trying restart Xcode and mac, but it’s doesn’t work.

**Comment by SpectralDragon** [comment]
I’m using Xcode 9.3.1

**Comment by kfchyc** [comment]
But apple has released the 9.4 version

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dan-zheng** [comment]
I downloaded Xcode 9.3.1 but wasn't able to replicate your bug: I created and ran the app without issue.

It's difficult for me to debug the Cocoa app without being able to replicate, unfortunately.
What version of macOS are you running? I'm on 10.13.3.

**Comment by kfchyc** [comment]
May I ask you a favor? Would you open your tool chain folder and put on the snapshot.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SpectralDragon** [comment]
@kfchyc what do you mean by ‘put on the snapshot’. In xcode I set swift tensorflow toolchain. My screenshots demonstrate this.

@dan-zheng macOS 10.13.3 too :(

**Comment by zhuiyizhiqiu** [comment]
<img width="570" alt="2018-05-30 8 26 45" src="https://user-images.githubusercontent.com/16648917/40720388-219e78e4-6449-11e8-918b-959d6d01de42.png">
<img width="961" alt="2018-05-30 8 36 11" src="https://user-images.githubusercontent.com/16648917/40720400-2ba7ed5c-6449-11e8-9810-238b8b3d7ab0.png">
I have the same question .

**Comment by zhuiyizhiqiu** [comment]
The Xcode version is 9.4.

**Comment by SpectralDragon** [comment]
I updated Xcode, create new Playground and all works fine, but macOS still crash with error about not loaded library `libtensorflow.so`. Maybe in `Build Settings` I should set path for this lib?

**Comment by dan-zheng** [comment]
Hi @SpectralDragon,
I wonder if the new [06-01 toolchain](https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages) works for you?

**Comment by SpectralDragon** [comment]
I'm try new build, but, it's doesn't work for me :c I will try install toolchain on new mac

**Comment by dan-zheng** [comment]
Hi @SpectralDragon,
Are you still encountering issues with the [06-01 toolchain](https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages)?

**Comment by dan-zheng** [comment]
Closing, as issues are not reproducible.

Please open a new bug if the [latest toolchain](https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages) does not work for you.
Note that Xcode 10 beta is required for toolchains 6/29 and newer.
Xcode 10 Playgrounds seem to work:
![screen shot 2018-06-30 at 4 28 42 am](https://user-images.githubusercontent.com/5590046/42124818-9cb136ce-7c1e-11e8-97d7-268578af818b.png)
