### ISSUE TITLE
It can build success,  but crash.

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [tensorflow/swift#351]
macOS: 10.15.2
swift for Tesnorflow : 0.6
When I run the code, the Xcode show build success.Then crash show
dyld: Library not loaded: @rpath/libswiftTensorFlow.dylib
  Referenced from: /Users/pengjuntao/Library/Developer/Xcode/DerivedData/S4TF-hflqrvhpqfipzreexeadgledjdys/Build/Products/Debug/S4TF
  Reason: no suitable image found.  Did find:
	/Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.6.xctoolchain/usr/lib/swift/macosx/libswiftTensorFlow.dylib: code signature in (/Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.6.xctoolchain/usr/lib/swift/macosx/libswiftTensorFlow.dylib) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)

<img width="752" alt="截屏2019-12-26下午4 11 17" src="https://user-images.githubusercontent.com/16648917/71466388-5afc1a80-27fa-11ea-9bd1-0854d1b72cc8.png">

**Comment by rahulbhalley** [comment]
@zhuiyizhiqiu try [this](https://github.com/tensorflow/swift/issues/177#issuecomment-569477582) solution.

**Comment by dan-zheng** [comment]
Thanks @rahulbhalley for sharing the solution!
I'll review https://github.com/tensorflow/swift/pull/352 soon so we can document the solution.

This validation issue seems to occur on only macOS Catalina, not Mojave.
