### ISSUE TITLE
[FEATURE_REQUEST]: Swift version of TF-Agents

### ISSUE THREAD

**Issue by maxvol** [tensorflow/swift#355]
Would it be possible to provide a Swift version of https://github.com/tensorflow/agents ?

**Comment by BradLarson** [comment]
While it isn't the same API and there isn't a one-to-one correspondence in terms of areas covered, you might want to take a look at [swift-rl](https://github.com/eaplatanios/swift-rl) and [swift-ale](https://github.com/eaplatanios/swift-ale). They provide reinforcement learning environments and agents, implemented in Swift.
