### ISSUE TITLE
"Couldn't lookup symbols" in macOS jupyter notebook (but OK in Xcode)

### ISSUE THREAD

**Issue by dbonner** [tensorflow/swift#361]
Hi,
I built S4TF with LLDB Python 3 support so that I could run Jupyter Notebook for macOS by checking out up to commit 7ffb598e6cef5d0373d2693dbadd97073e3c71d8 so that I avoided the regression that prevents swiftPM being built.
The following code (from the Python Interoperability notebook) results in "Couldn't lookup symbols" in Jupyter.  However, if you run the code in XCode it runs OK:

import TensorFlow

import Python

print(Python.version)

let np = Python.import("numpy")
print(np)
let zeros = np.ones([2, 3])
print(zeros)

import TensorFlow

let numpyArray = np.ones([4], dtype: np.float32)
print("Swift type:", type(of: numpyArray))
print("Python type:", Python.type(numpyArray))
print(numpyArray.shape)

// Examples of converting `numpy.ndarray` to Swift types.
let array: [Float] = Array(numpy: numpyArray)!
let shapedArray = ShapedArray<Float>(numpy: numpyArray)!
let tensor = Tensor<Float>(numpy: numpyArray)!

// Examples of converting Swift types to `numpy.ndarray`.
print(array.makeNumpyArray())
print(shapedArray.makeNumpyArray())
print(tensor.makeNumpyArray())

// Examples with different dtypes.
let doubleArray: [Double] = Array(numpy: np.ones([3], dtype: np.float))!
let intTensor = Tensor<Int32>(numpy: np.ones([2, 3], dtype: np.int32))!

You get the right answer to the last bit of code with Xcode:
3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:08:30) 
[Clang 9.0.1 ]
<module 'numpy' from '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/__init__.py'>
[[1. 1. 1.]
 [1. 1. 1.]]
Swift type: PythonObject
Python type: <class 'numpy.ndarray'>
(4,)
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]

With Jupyter you get the following for the final outpu of codet:
3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)]
<module 'numpy' from '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/__init__.py'>
[[1. 1. 1.]
 [1. 1. 1.]]
Swift type: PythonObject
Python type: <class 'numpy.ndarray'>
(4,)
Error: Couldn't lookup symbols:
  (extension in TensorFlow):TensorFlow.Tensor< where A: Python.NumpyScalarCompatible>.makeNumpyArray() -> Python.PythonObject
  (extension in TensorFlow):TensorFlow.Tensor< where A: Python.NumpyScalarCompatible>.makeNumpyArray() -> Python.PythonObject
  (extension in TensorFlow):TensorFlow.Tensor< where A: Python.NumpyScalarCompatible>.makeNumpyArray() -> Python.PythonObject
  (extension in TensorFlow):TensorFlow.Tensor< where A: Python.NumpyScalarCompatible>.makeNumpyArray() -> Python.PythonObject
  (extension in TensorFlow):TensorFlow.Tensor< where A: Python.NumpyScalarCompatible>.makeNumpyArray() -> Python.PythonObject
  (extension in TensorFlow):TensorFlow.Tensor< where A: Python.NumpyScalarCompatible>.makeNumpyArray() -> Python.PythonObject

**Comment by dan-zheng** [comment]
Can you please describe how you built and installed [swift-jupyter](https://github.com/google/swift-jupyter)? Did you build a macOS toolchain with LLDB built with Python 3, then used that toolchain to build swift-jupyter?

I don't believe swift-jupyter builds are officially supported on macOS (since we release [macOS toolchains built with Python 2.7](https://github.com/tensorflow/swift/blob/master/Installation.md#development-snapshots)), but I tried building a toolchain with Python 3 and installing swift-jupyter natively worked.

---

If a native installation isn't important to you, you can install swift-jupyter [via Docker](https://github.com/google/swift-jupyter#option-3-using-the-docker-container). This is how I use swift-jupyter on macOS.

**Comment by dbonner** [comment]
Hi,
I did build the swift macOs toolchain with LLDB built with Python 3.  I can get the correct result for most Swift and S4TF commands using jupyter notebook with the swift-jupyter kernel.  It's just this bit of code it does not work with:

let doubleArray: [Double] = Array(numpy: np.ones([3], dtype: np.float))!
let intTensor = Tensor(numpy: np.ones([2, 3], dtype: np.int32))!

Error: Couldn't lookup symbols:
(extension in TensorFlow):TensorFlow.Tensor< where A: Python.NumpyScalarCompatible>.makeNumpyArray() -> Python.PythonObject

The code executes properly in Xcode and in swift-jupyter installed on Ubuntu.

The exact steps I took to build the macOS toolchain and install swift-jupyter were:

1. brew install python  (installs the python 3 headers needed for LLDB python 3 support)
2. brew install python@2
3. pip2 install numpy future six
4. brew install cmake ninja
5. brew cask install java
6. ./bazel-0.27.1-installer-darwin-x86_64.sh
7. mkdir swift-source
8. cd swift-source
9. git clone https://github.com/apple/swift.git -b tensorflow
10. ./swift/utils/update-checkout --clone --scheme tensorflow
11. cd swift
12. utils/build-toolchain-tensorflow
13. (This builds swift.  I extract swift and then extract symbols to /Library/Developer/Toolchains)
14. python3 -m venv venv
15. . venv/bin/activate
16. pip3 install -r requirements.txt
17. python register.py --sys-prefix --swift-toolchain /Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-13-a.xctoolchain
18. jupyter notebook

Since this error does not occur in Ubuntu, I'm guessing you would advise me to use jupyter notebooks in an Ubuntu docker or vm?
All the best,
Daniel

**Comment by shabalind** [comment]
Hi @dbonner, currently we don't officially support swift-jupyter on macOS. Please use Ubuntu in a VM or docker for swift-jupyter, or, alternatively use Xcode on macOS. Unfortunately there is no worksheet-style environment for macOS at the time. 

If someone from the community would like to work on this, contributions are welcome! TF-500 tracks progress that blocks Xcode Playgrounds from being support for S4TF. 

Thanks for the report!

**Comment by marcrasi** [comment]
A hint about how to debug this: Open the Swift REPL, run `:log enable lldb all`, then run the problematic code. There might be some log messages about not being able to load a shared library or something.

**Comment by dbonner** [comment]
@marcrasi  When I run `:log enable lldb all` using the S4TF REPL, I just get the following line as output repeated every few seconds as a log message:
this = 0x00007FCD65C00170, timeout = 5000000 us
The message does not change regardless of what I run with the swift-jupyter kernel.
Maybe I'm doing this wrong?

**Comment by marcrasi** [comment]
Ah sorry for the confusion, I meant to run the problematic code in the Swift REPL where you enabled logging, not in swift-jupyter.
