### ISSUE TITLE
Could I use Artistic License 2.0 to translate the documents to Chinese?

### ISSUE THREAD

**Issue by CharlotteFallices** [tensorflow/swift#384]

**Comment by lamberta** [comment]
Hi @CharlotteFallices,

Thanks for your interest. There's currently a Chinese community translation effort over in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo. You can make a `site/zh-cn/swift/` directory for translated notebooks. (The Korean folks have also started this for S4TF, see [their directory](https://github.com/tensorflow/docs-l10n/tree/master/site/ko/swift).)

See the community translations section of the docs contributor guide: https://tensorflow.google.cn/community/contribute/docs#community_translations
There's also a mailing list you can join: [docs-zh-cn@tensorflow.org](https://groups.google.com/a/tensorflow.org/forum/#!forum/docs-zh-cn)

No need to change the license---we use the Creative Commons Attribution 4.0 License for text and the Apache 2.0 License for code. This is displayed the bottom of the pages on tensorflow.org.

The community translation project is for [tensorflow.google.cn/swift](https://www.tensorflow.org/swift) (the [docs/site](https://github.com/tensorflow/swift/tree/master/docs/site) directory in this repo), not the design docs.
