### ISSUE TITLE
differentiation of coroutine calls is not yet supported

### ISSUE THREAD

**Issue by pedronahum** [tensorflow/swift#388]
Hi,

I am testing S4TF for financial applications given the AD capabilities. And I am facing an issue that i have not seen documented or raised. Your guidance is greatly appreciated.

In particular, when an array is updated in a loop, the code below will fail to compile (S4TF v0.7-rc2 Ubuntu CPU Only). The same code will crash Google Colab.

```swift
struct PathCalc : Differentiable  {
  @noDerivative let N: Int
  @noDerivative let Nmat: Int
  @noDerivative let Delta: Float
  @noDerivative let Z: Float

  @differentiable(wrt: (Rates, Lambda))
  func applied(Rates:Array<Float>,Lambda:Array<Float> ) -> Array<Float> {

    var L  = Array<Float>(repeating: 0.0,count: N)
    let sq = Delta.squareRoot()

    for n in 0...Nmat-1{
      let sqez = sq*Z
      var v = Float(0)
      
      for i in n+1...N-1{
        let lam = Lambda[i - n - 1 ]
        let con1 = Delta*lam
        v = v + (con1*Rates[i])/(1.0 + Delta*L[i])
        let first = con1*v
        let second = lam*(sqez - 0.5*con1)
        let vrat = exp(first + second)    
	L[i] = Rates[i]*vrat
      }
    }
    return L
  }
 
}
```
If I attempt to get the gradient of the code above, I will get an error
```batch
test.swift:10:4: error: function is not differentiable
  @differentiable(wrt: (Rates, Lambda))
  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.swift:11:8: note: when differentiating this function definition
  func applied(Rates:Array<Float>,Lambda:Array<Float> ) -> Array<Float> {
       ^
test.swift:27:7: note: differentiation of coroutine calls is not yet supported
        L[i] = Rates[i]*vrat

```
Clearly the code above is finance-specific, and it relates to adjoint calculations of financial derivatives (see, for example, http://people.maths.ox.ac.uk/~gilesm/codes/libor_AD/). I just felt that it could be a very good way to raise awareness in the finance industry of the great work you guys are doing here.

Best,

Pedro N.

**Comment by dan-zheng** [comment]
Automatic differentiation is implemented in the Swift compiler, so Issues related to automatic differentiation are actually tracked at https://bugs.swift.org, not at https://github.com/tensorflow/swift. Please file issues there!

I shared a more thorough explanation and workaround here: https://github.com/tensorflow/swift-models/issues/326#issuecomment-586754811.
