### ISSUE TITLE
Python tutorial broken

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift#405]
If you run the python interoperability notebook:
https://colab.research.google.com/github/tensorflow/swift/blob/master/docs/site/tutorials/python_interoperability.ipynb

One gets the error in the first code block of:
error: <Cell 25>:2:1: error: unexpected conditional compilation block terminator
#else
^

error: <Cell 25>:4:1: error: unexpected conditional compilation block terminator
#endif
^

This was reported by a user at: https://groups.google.com/a/tensorflow.org/g/swift/c/_HMOs8UNcpo

**Comment by ematejska** [comment]
If I add "import TensorFlow" before the #if-else-endif import block, it starts working again.  Why is this required?  The #if-else-endif import block was added recently as part of adding PythonKit.

**Comment by ematejska** [comment]
In the very least, we should update the notebook.

**Comment by marcrasi** [comment]
I was updating a different notebook this morning with exactly this problem, so I know what it is.

Colab treats the first line as a comment if it begins with "#". So adding any line above the "#if" line fixes it.
