### ISSUE TITLE
Windows Installation -- Variables UniversalCRTSdkDir and VCToolsInstallDir

### ISSUE THREAD

**Issue by pedronahum** [tensorflow/swift#413]
Hi,

It seems that some environmental variables are require to setup the visualc and ucrt modules. But I think these are not part of VS 2019. For example: UniversalCRTSdkDir and VCToolsInstallDir. 

Step 4 defines SDKROOT, but not the ones mentioned above. 

Any guidance here is greatly appreciated. 

Thanks!!!

Pedro N.

**Comment by compnerd** [comment]
These variables are part of visual studio and are defined by VsDevEnv.cmd when you run there x64 Native Tools Command Prompt.  Note that this is *NOT* the same as Command Prompt.

**Comment by pedronahum** [comment]
Hi @compnerd 

You are right! Many thanks for getting back me.
