### ISSUE TITLE
AD - simplest example

### ISSUE THREAD

**Issue by johndpope** [tensorflow/swift#42]
Version 9.4 (9F1027a)
Toolchain: Swift for TensorFlow Development Snapshot 2018-06-01

I'm toying around with automatic differentiation - thus far

func cube(_ x: Float, _ str: String) -> Float {
    print(str)
    return x * x * x
}

    let dCube_dx = #gradient(of: cube, withRespectTo: .0)
    let _ =  cube(5, "hi")  // prints "hi" and returns 125
    let _ = dCube_dx(5, "hi") // prints "hi" and returns 75

![screen shot 2018-06-11 at 14 45 19](https://user-images.githubusercontent.com/289994/41250868-2ded1b50-6d86-11e8-9110-518888fc07d3.png)

reading the docs - it says this is still under development.
https://github.com/tensorflow/swift/blob/master/docs/AutomaticDifferentiation.md
I'll leave this open for now.

**Comment by rxwei** [comment]
Thank you for opening this issue. Swift for TensorFlow is not yet ready for general use, as made clear on the homepage. And many planned features are known to be unimplemented or buggy. The core team is actively implementing missing features.
