### ISSUE TITLE
noob question, Xcode build OS version

### ISSUE THREAD

**Issue by briantimar** [tensorflow/swift#425]
Hi! - 

I'm using macOS 10.15, with the S4TF 04/17 toolchain. Having followed the prebuilt installation instructions I can compile code with ```swift``` from the command line,  but in Xcode (11.4.1), at ```import TensorFlow``` I get a compiler error: "Compiling for macOS 10.10, but module 'TensorFlow' has a minimum deployment target of macOS 10.13". 

Any idea why? Obviously that OS version is wrong, but I can't find anything in xcode settings to alter this.

**Comment by dan-zheng** [comment]
Check the "Deployment Target" for your Xcode target:

<img width="955" alt="Screen Shot 2020-04-23 at 2 39 04 AM" src="https://user-images.githubusercontent.com/5590046/80084709-15333280-850c-11ea-96da-b5cc39baa555.png">

Is it set to macOS 10.10? If so, you can try setting it to macOS 10.13 or newer.

**Comment by briantimar** [comment]
that's it, thank you! had incorrect xcode project structure
