### ISSUE TITLE
Build 𝛁Swift without TensorFlow

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift#437]
Based on @BradLarson's response [here](https://groups.google.com/a/tensorflow.org/d/msg/swift/-6ivNuah6rY/76zcJLvyBQAJ) it looks like it must be possible to build Swift with _differentiation_ feature (excluding `TensorFlow` module). Currently every toolchain released by Google's S4TF team includes `TensorFlow` module in it whereas I want to build and use 𝛁Swift without it (just differentiation).

Can somebody please help me with that?

cc @dan-zheng @dabrahams @rxwei

**Comment by dan-zheng** [comment]
Sure, try using Swift toolchains from https://swift.org/download! These are built from [`apple/swift` master branch](https://github.com/apple/swift/tree/master).

You can use differentiable programming features by importing the `_Differentiation` module: `Differentiable` protocol, `@differentiable` and `@derivative` attributes, and differential operators.

This is a bit different from Swift for TensorFlow toolchains ([`apple/swift` tensorflow branch](https://github.com/apple/swift/tree/tensorflow)), which don't currently require the import but will someday.

**Comment by rahulbhalley** [comment]
Hey @dan-zheng, I downloaded Swift 5.2.3 RELEASE 2020-04-28 (a) toolchain from swift.org and following happened. ☹️

Um, I am able to `import _Differentiation`. I can define differentiable functions with `@differentiable` attribute.

But there are none of the followings (therefore, I cannot use them):
1.  **differentiable APIs** (`gradient(at:in:)`, `valueWithGradient(at:in:)`, and their variants)
2. **define custom derivatives** (`differentiating(wrt:)`), and so on.

Also defining custom differentiable type in S4TF toolchain is simple as:
```swift
struct Some: Differentiable {
  var x, y: Float
}
```

But using the apple/swift master toolchain from swift.org I cannot do this and am forced to give type for `typealias TangentVector = type`. Weird. 

It looks like the apple/swift master toolchains are not yet ready to be entitled as 𝛁Swift. Or am I missing something that is halting me from doing all differentiation with this toolchain?

**Comment by dan-zheng** [comment]
Hi Rahul,

Sorry for not clarifying! Please download a development snapshot toolchain, those are built ~nightly from `apple/swift` master branch and have latest differentiable programming changes.

<img width="779" alt="Screen Shot 2020-05-02 at 8 50 57 AM" src="https://user-images.githubusercontent.com/5590046/80868937-4d481d00-8c52-11ea-977f-1102200a0b7f.png">

Release toolchains are built less frequently, so they won't have latest differentiable programming changes. [Swift 5.2.3 was released in March 2020](https://swift.org/blog/swift-5-2-released/) before differentiable programming features were fully upstreamed to master.

**Comment by dan-zheng** [comment]
I personally use `swiftenv` for managing toolchains on macOS (both from [swift.org/download](https://swift.org/download) and S4TF) and recommend it! https://github.com/tensorflow/swift/issues/360

**Comment by rahulbhalley** [comment]
Hmm, that development master toolchain still have `TensorFlow` module.

**Comment by rahulbhalley** [comment]
There is no `@differentiating(wrt:)` attribute to define my own derivative for a function. 

Any timeline on when will this (and other differentiation features) will land into apple/swift master?

**Comment by dan-zheng** [comment]
> There is no `@differentiating(wrt:)` attribute to define my own derivative for a function.

`@differentiating(foo, wrt: ...)` was renamed to `@derivative(of: foo, wrt: ...)` a few months ago.

[Here's the related section from the Differentiable Programming Manifesto.](https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md#make-a-function-differentiable-using-derivative-or-transpose)
[We plan to start Differentiable Swift usage documentation soon](https://forums.swift.org/t/trajectory-for-evaluating-adding-automatic-differentiation-to-swift/30048/7?u=dan-zheng) that should be more accessible.
