### ISSUE TITLE
Add libSIL to CI

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift#439]
Imported from JIRA https://bugs.swift.org/browse/TF-752

Type: | Task | Priority: | Minor
-- | -- | -- | --
Reporter: | Eugene Burmako | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | None

Now that libSIL has been opensourced at https://github.com/tensorflow/swift, it may make sense to get it into CI.

**Comment by BradLarson** [comment]
I don't think we have near-term plans to use libSIL for much, so we probably don't need to set up CI for it as previously planned.
