### ISSUE TITLE
Trouble downloading S4TF Xcode 11 (May 3, 2020) Development Snapshot

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift#442]
Instead of downloading I get the following page at [this download link](https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2020-05-03-a-osx.pkg):

<img width="1375" alt="Screen Shot 2020-05-04 at 5 18 10 PM" src="https://user-images.githubusercontent.com/9640948/80962859-766fd580-8e2b-11ea-8401-27cd6bddae45.png">

**Comment by dan-zheng** [comment]
Fixed: https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2020-05-03-a-osx.pkg
