### ISSUE TITLE
No such module 'TensorFlow'

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift#471]
**Toolchain**: Xcode 11 (May 26, 2020) Development Snapshot
**OS**: macOS Catalina 10.15.4 (19E287)
**Xcode**: Version 11.5 (11E608c)

**Comment by dan-zheng** [comment]
Thanks for the report! Looking into it now.
Also adding workflow tests so these errors don't happen in the future.

**Comment by dan-zheng** [comment]
The toolchain link should now be fixed: https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2020-05-26-a-osx.pkg

Please you please confirm and close the issue?

**Comment by rahulbhalley** [comment]
Thanks, it's working now.
