### ISSUE TITLE
GCP image 

### ISSUE THREAD

**Issue by sinamoeini** [tensorflow/swift#472]
Hi Team, 

Since swift for tensorflow has a new release every couple of months, it would be great if you could provide a GCP disk image alongside like python TensorFlow. This is very helpful for those of us who use google cloud platform.

Thanks!

**Comment by texasmichelle** [comment]
Hi Sina! Just to confirm your request - are you referring to a machine image like these, the [Deep Learning VMs](https://cloud.google.com/ai-platform/deep-learning-vm/docs/images)?

**Comment by sinamoeini** [comment]
Hi Michelle. Yes that’s it. Thanks.

**Comment by texasmichelle** [comment]
I agree that having an S4TF version of these images would be great! I've added this request to the DLVM team's queue. In the meantime, you can use [this script](https://github.com/tensorflow/swift/blob/master/utils/install-ubuntu1804.sh) to install the S4TF toolchain on a GCE instance with a stock Ubuntu 18.04 image.

**Comment by texasmichelle** [comment]
You could automate setup with something like this:
```
mkdir -p ~/repos/tensorflow
git clone https://github.com/tensorflow/swift.git ~/repos/tensorflow/swift
sudo ~/repos/tensorflow/swift/utils/install-ubuntu1804.sh \
  --toolchain-url https://storage.googleapis.com/swift-tensorflow-artifacts/releases/v0.9/rc1/swift-tensorflow-RELEASE-0.9-ubuntu18.04.tar.gz
export PATH="${HOME}/swift-toolchain/usr/bin:$PATH"
```

**Comment by sinamoeini** [comment]
Thank you very much!

**Comment by texasmichelle** [comment]
Good news! A DLVM image with S4TF for CPU and CUDA 11 will be released as experimental next week 🎉

**Comment by texasmichelle** [comment]
I will update this thread with the gcloud command once it's live.

**Comment by texasmichelle** [comment]
A set of S4TF experimental DLVM images are now live 🚀  To find them, run:
```
gcloud compute images list --project deeplearning-platform-release --no-standard-images | grep swift
```

As an example of how to create a small GCE instance using the cpu image:

```
gcloud compute instances create s4tf-ubuntu \
  --image-project=deeplearning-platform-release \
  --image-family=swift-latest-cpu-ubuntu-1804 \
  --maintenance-policy=TERMINATE \
  --machine-type=n1-standard-2 \
  --boot-disk-size=256GB
```

I will add this to our docs in a bit more detail.

**Comment by texasmichelle** [comment]
Docs additions here: https://github.com/tensorflow/swift/pull/548
