### ISSUE TITLE
No such module ‚TensorFlow‘

### ISSUE THREAD

**Issue by saschaschramm** [tensorflow/swift#48]
With Xode 10 (Beta 3) and toolchains 
swift-tensorflow-DEVELOPMENT-2018-06-29-a-osx.pkg and 
swift-tensorflow-DEVELOPMENT-2018-07-12-a-osx.pkg
I get an error when trying to import TensorFlow into a Command Line project:
```
No such module ‚TensorFlow‘
```
In playground and Swift REPL everything is working fine:
```
Welcome to Swift version 4.2-dev (LLVM eb00ef6046, Clang d9545f2833, Swift 3d37ae7c06). Type :help for assistance.
  1> import TensorFlow
  2>  
```

When using Xode 9.4.1 and toolchain swift-tensorflow-DEVELOPMENT-2018-06-25-a-osx.pkg an import of TensorFlow into a Command Line project is possible.

Environment:
macOS 10.13.6

**Comment by rxwei** [comment]
Xcode 10 beta doesn't work very well with third-party toolchains. A workaround is the following:

* Go to "File" - "Project Settings"
* Set "Build System" to "Legacy Build System"
* Click "Done".

**Comment by saschaschramm** [comment]
Great, that works. Thanks!
