### ISSUE TITLE
Works in Playground, But doesn't works in macOS command line project

### ISSUE THREAD

**Issue by aaaron7** [tensorflow/swift#51]
I can run `import TensorFlow` in Xcode playground, but when i run it in the macOS command line project. it always raise "No such module TensorFlow" error.

My environment: Xcode 10 beta4, macOS 10.14 Beta, with latest Swift for TensorFlow toolchain .

**Comment by rxwei** [comment]
By "macOS command line project" did you mean a command-line project in Xcode? If so, this is a known Xcode issue that can be worked around. See https://github.com/tensorflow/swift/issues/48.

**Comment by aaaron7** [comment]
@rxwei Yes, exactly same problem. thanks!
