### ISSUE TITLE
Specify Pre-Built Package Compatibility - Xcode

### ISSUE THREAD

**Issue by ericmx** [tensorflow/swift#52]
Hello,

Would it be possible to specify the Xcode version for the older pre-built packages listed here: https://github.com/tensorflow/swift/blob/master/Installation.md

For example, will June 25th release work with Xcode 9.4, or is it Xcode 10 only? Etc.

Thank you

**Comment by dan-zheng** [comment]
Done in https://github.com/tensorflow/swift/commit/ed295c3eb5263fafee123c2db979d153a4e9dd33.
Toolchains June 25th and older work with Xcode 9, but not 10.
June 29th and newer work with Xcode 10, but not 9.

**Comment by ericmx** [comment]
Thank you for the assistance!
