### ISSUE TITLE
Recent development snapshots cause Xcode runtime popup: "LLDB provided no error string"

### ISSUE THREAD

**Issue by porterchild** [tensorflow/swift#532]
The build succeeds, but there is immediately an Xcode dialog popup: 
"Could not launch <ProjectName> LLDB provided no error string". 
The center console at the top of Xcode immediately reads "Finished running <ProjectName>", with no program output in the console (not even the usual "Program ended with exit code: 0").

This has happened for a few small projects, and even happens with a small or empty program. I've tried with recent toolchains, including the August 26 snapshot, on Xcode 11.4.1, Xcode 12 beta 4, and Xcode 12 beta 6.

The v0.11 release doesn't cause this popup.

**Comment by dan-zheng** [comment]
Thanks for reporting. Could you please share a minimal project reproducing the issue?

I wasn't able to reproduce the issue with either a [minimal Xcode project](https://github.com/dan-zheng/swift-apis/tree/issue-532-xcode-project) or a SwiftPM package using the [`tensorflow-DEVELOPMENT-2020-09-03-a` macOS toolchain](https://storage.googleapis.com/swift-tensorflow-artifacts/macos-toolchains/swift-tensorflow-DEVELOPMENT-2020-09-03-a-osx.pkg) and Xcode 12 beta 4.

Running in Xcode succeeds without any error dialog:

![demo](https://user-images.githubusercontent.com/5590046/92639122-3b295b80-f290-11ea-8f66-d3e64ddb167c.png)

**Comment by porterchild** [comment]
I just did a bisect with your minimal Xcode project and found that the change is on the 8/05 toolchain. Before that, the popup doesn't happen. Starting on 8/05, the popup happens no matter the project. This is the same for Xcode 11.4, 12 beta 4 and 12 beta 6 on my machine.
I was starting to think there was just something wrong with my Xcode installations, but I just had two colleagues try with the 9/03 toolchain and the popup happened there as well. All three computers are on MacOS 10.15.6. I hope the bisect date gives you some clue... Sorry I don't have any more context. Googling hasn't been helpful yet.

<img width="663" alt="Screen Shot 2020-09-09 at 1 57 49 PM" src="https://user-images.githubusercontent.com/25194119/92647002-76358a00-f2a4-11ea-9b07-f3455fcab152.png">

<img width="550" alt="Screen Shot 2020-09-09 at 1 58 04 PM" src="https://user-images.githubusercontent.com/25194119/92647032-7d5c9800-f2a4-11ea-8834-ddf1aae5b59c.png">

**Comment by porterchild** [comment]
I get the same popup in Xcode 12.0

**Comment by dan-zheng** [comment]
Thanks for sharing all the context! Unfortunately, I still wasn't able to reproduce the issue ([screen recording](https://youtu.be/YIZSmbYF-Ws)).

Environment:
- macOS 10.15.6
- Xcode 12 beta 4
- [swift-tensorflow-DEVELOPMENT-2020-09-16-a.xctoolchain](https://storage.googleapis.com/swift-tensorflow-artifacts/macos-toolchains/swift-tensorflow-DEVELOPMENT-2020-09-16-a-osx.pkg)

Does anyone have ideas on how to reproduce the issue?

**Comment by porterchild** [comment]
As a temporary workaround, I found that the issue goes away if I uncheck Target-> Edit Scheme -> Run -> Info -> Debug executable.
Of course I don't have a debugger if I uncheck that box. So I can run, but can't use breakpoints or anything else the debugger provides.

**Comment by porterchild** [comment]
I've found that if I start Xcode as superuser from the command line with `sudo /Applications/Xcode.app/Contents/MacOS/Xcode`, the popup doesn't happen. So it seems there's a permissions issue causing trouble(?)

**Comment by porterchild** [comment]
If I run Xcode from the command line with `/Applications/Xcode.app/Contents/MacOS/Xcode`, then each time I run and the popup happens, the console prints this:

```  
  Reason: imagdyld: Library not loaded: @rpath/Python3.framework/Versions/3.8/Python3
  Referenced from: /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-09-16-a.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB
  Reason: image not found
 not loaded: @rpath/Python3.framework/Versions/3.8/Python3
  Referenced from: /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-09-16-a.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB
error: failed to send packet 0000000e
error: failed to receive response for packet (sequence ID 0000000e)
error: failed to send packet 0000000f
error: failed to receive response for packet (sequence ID 0000000f)
error: failed to send packet 00000010
error: failed to receive response for packet (sequence ID 00000010)
```

Feels like I'm close!

**Comment by porterchild** [comment]
After adding a non-`Xcode-beta.app` rpath with
`sudo install_name_tool -add_rpath /Applications/Xcode.app/Contents/Developer/Library/Frameworks/ <toolchain path>/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB`

It works!
I guess a normal `Xcode.app` path should be added by default? @dan-zheng

**Comment by porterchild** [comment]
@ematejska @texasmichelle  this issue might be important to reference when making the new MacOS toolchains

**Comment by VladimirBessonov** [comment]
> After adding a non-`Xcode-beta.app` rpath with
> `sudo install_name_tool -add_rpath /Applications/Xcode.app/Contents/Developer/Library/Frameworks/ <toolchain path>/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB`
> 
> It works!
> I guess a normal `Xcode.app` path should be added by default? @dan-zheng

what is toolchain path in your answer?

**Comment by andrekandore** [comment]
> > After adding a non-`Xcode-beta.app` rpath with
> > `sudo install_name_tool -add_rpath /Applications/Xcode.app/Contents/Developer/Library/Frameworks/ <toolchain path>/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB`
> > It works!
> > I guess a normal `Xcode.app` path should be added by default? @dan-zheng
> 
> what is toolchain path in your answer?

i had installed the swift 5.5 toolchain and had the exact same issue, i fixed it like below:
(please note, both xcode and toolchain are installed to my local user, not the normal global space)

```
install_name_tool -add_rpath ~/Applications/Xcode.app/Contents/Developer/Library/Frameworks ~/Library/Developer/Toolchains/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-08-11-a.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB
```

as you can see `~/Library/Developer/Toolchains/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-08-11-a.xctoolchain/` is the toolchain part

i think in normal installation scenario, that is in `/Library` instead of `~/Library`

hope that helps 😅
