### ISSUE TITLE
[Readme] Graphic Not Loading

### ISSUE THREAD

**Issue by rakesh4real** [tensorflow/swift#538]
Graphic pertaining to CI build status not loading @ https://github.com/apple/swift/tree/tensorflow#building-swift-for-tensorflow

![image](https://user-images.githubusercontent.com/45640029/94206854-064e1300-fee4-11ea-9594-08250f65b840.png)

**Comment by compnerd** [comment]
https://github.com/apple/swift/pull/34162 should address this

**Comment by compnerd** [comment]
I believe that this should be resolved now.
