### ISSUE TITLE
Weird bugs in working with ParameterAggregate

### ISSUE THREAD

**Issue by aaaron7** [tensorflow/swift#54]
OS: macOS Mojava Beta
Toolchain: Xcode 10/7-24

I found if I:
1). use `update` method of `ParameterAggregate`;
2). print some tensor related information in each iteration；

the program will frozen after 1 or 2 times iteration during the execution, or sometime will cause to compilation error  which message is "#tfop invalid: FIXME: cannot lower a Host->TF tensor transfer in a loop header"

Remove `print` or `update` fix the problem. (`matmul` or •  works fine with `print` ) 

> sometimes `print(loss)` works fine but `print("\(loss)")` will trigger compilation error above.

Test code:

```swift
struct Weights : ParameterAggregate {
    var w = Tensor<Float>([[1,2],[3,4]])
}

func train_test(_ x : inout Weights)
{
    for i in 0...3
    {
        let grad = Weights()
        x.update(withGradients : grad){ (p,g) in 
            p = g * 0.0001
        }
        print(i)
        let result = x.w.mean()
        print(result)
    }
}

var weight = Weights()
train_test(&weight)
```

**Comment by aaaron7** [comment]
Sorry, maybe I mistakenly removed the key code which can reproduce the error, after simplify the code.

My swift version:
Swift version 4.2-dev (LLVM 748f9878c8, Clang 6c624d9bad, Swift 15f32c49ee)
Target: x86_64-apple-darwin18.0.0

The following code can reproduce the error (added a tensor parameter to train function)

```swift
import TensorFlow
struct Weights : ParameterAggregate {
    var w = Tensor<Float>([[1,2],[3,4]])
}

func train_test(_ x : inout Weights, _ temp : Tensor<Float>)
{
    for i in 0...3
    {
        let grad = Weights()
        x.update(withGradients : grad){ (p,g) in
            p = g * 0.0001
        }
        print(i)
        let result = x.w.mean()
        print(result)
    }
}

var weight = Weights()
train_test(&weight, Tensor<Float>(randomNormal:[2,2]))
```

**Comment by dan-zheng** [comment]
Thanks, I'm able to reproduce the error on the 7/24 toolchain now.

This bug has been fixed upstream (tested with https://github.com/apple/swift/commit/6da8496ed830fe8bc07f1916960529562fdc4d03): the program terminates without hanging:
```
0
0.00024999998
1
0.00024999998
2
0.00024999998
3
0.00024999998
```

I'll leave this bug open until a new toolchain is released.

**Comment by rxwei** [comment]
New toolchains have been released.
https://github.com/tensorflow/swift/blob/master/Installation.md
