### ISSUE TITLE
README links to Archived apple/swift-lldb repo

### ISSUE THREAD

**Issue by xanderdunn** [tensorflow/swift#542]
The [apple/swift-lldb](https://github.com/apple/swift-lldb/tree/tensorflow) repo is archived and hasn't seen any updates since October 2019. 

The README in this repo still refers to the "Swift fork of LLDB" with a link to the archived apple/swift-lldb repo. Is there a new reference it should be updated to?

**Comment by xanderdunn** [comment]
Maybe it's [apple/llvm-project](https://github.com/apple/llvm-project)? As indicated by:
```
$ which lldb
/home/xander/swift-tensorflow-RELEASE-0.10-cuda10.2-cudnn7-ubuntu18.04/usr/bin/lldb
$ lldb --version
lldb version 10.0.0 (https://github.com/apple/llvm-project.git revision 55d27a5828841a530b402bbe17df84580115065e)
Swift version 5.3-dev (LLVM 55d27a5828, Swift 6a5d84ec08)
```

**Comment by dan-zheng** [comment]
Thanks! Updated in https://github.com/tensorflow/swift/pull/590.
