### ISSUE TITLE
How can I confirm that s4tf is working

### ISSUE THREAD

**Issue by zhaoyueplc** [tensorflow/swift#551]
Hi ,
Would you help  confirm this  problem ?

swift 5.3 installed in my ubuntu:
 zhaoyue@zhaoyue-virtual-machine:~$ swift -version
Swift version 5.3-dev (LLVM 582da3a4d2e364f, Swift e141661981cd757)
Target: x86_64-unknown-linux-gnu
and for your guide, i am test the installation:
zhaoyue@zhaoyue-virtual-machine:~$ swiftc test.swift
zhaoyue@zhaoyue-virtual-machine:~$ test

But no response after test. 

 I notice that a new file is generated in the same path, and executing it directly can get the result.
zhaoyue@zhaoyue-virtual-machine:~$ ./test 
[[2.0, 4.0],
 [6.0, 8.0]]

But I don't know if swiftc comes from swift or s4tf? By the way, I would like to know if the above installation  is correct?

I would appreciate it if you could give me a reply .

**Comment by brettkoonce** [comment]
`which swift` should tell you where your swift install is, which should match where you installed s4tf.

adding an `import TensorFlow` call to the top of your test file would show you quickly whether or not the right libraries are being pulled in.

**Comment by saeta** [comment]
@brettkoonce is absolutely right. In addition, one other way to verify that everything is working would be to clone [swift-models](https://github.com/tensorflow/swift-models) and run `swift run -c release Fractals MandelbrotSet` (see details at https://github.com/tensorflow/swift-models/tree/master/Examples/Fractals).
