### ISSUE TITLE
import PythonKit with S4TF toolchain on local machine

### ISSUE THREAD

**Issue by tylerdarwin3** [tensorflow/swift#556]
Using CLion with Swift plug-in, I see this error after adding PythonKit into my build dependencies:

Compiling Swift_Cpp main.swift
error: compiling for macOS 10.10, but module ‘PythonKit’ has minimum deployment target of macOS 10.13: /Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.11.xctoolchain/usr/lib/swift/macosx/PythonKit.swiftmodule/x86_64.swiftmodule

for reference, this was added to build dependencies: 
.package(url: "https://github.com/pvieito/PythonKit.git", .branch("master")), 

but `import PythonKit` yielded the error shown above.

**Comment by BradLarson** [comment]
I'm not sure where the minimum deployment target requirement is coming from, but one fix for this on macOS is to specify

```swift
platforms: [
        .macOS(.v10_13),
    ],
```

in your Package, like is done [here](https://github.com/tensorflow/swift-models/blob/master/Package.swift#L8) in swift-models. That will set the minimum macOS deployment target to 10.13 and satisfy the above. You won't see this error on Linux or other platforms, just macOS.
