### ISSUE TITLE
"Sharp edges in Differentiable Swift" executable code

### ISSUE THREAD

**Issue by marcrasi** [tensorflow/swift#560]
It would be nice to change the code in https://github.com/tensorflow/swift/blob/master/docs/site/tutorials/Swift_autodiff_sharp_edges.ipynb into executable code, with some example invocations, so that we can easily verify that it still works every time we release a new toolchain.

**Comment by porterchild** [comment]
I think this can be closed. I don't see the button to do so on my screen.

**Comment by porterchild** [comment]
@marcrasi
