### ISSUE TITLE
Model training walkthrough produces: Fatal error: 'try!' expression unexpectedly raised an error: Python exception: No module named 'matplotlib'

### ISSUE THREAD

**Issue by arielelkin** [tensorflow/swift#566]
I'm following the Tensorflow [Model training walkthrough](https://www.tensorflow.org/swift/tutorials/model_training_walkthrough), but I'm getting a runtime error very early on, at this line:

```swift
import TensorFlow
import PythonKit

let plt = Python.import("matplotlib.pyplot")
```

the error is:
```
Fatal error: 'try!' expression unexpectedly raised an error: Python exception: No module named 'matplotlib': file PythonKit/Python.swift, line 673
2020-11-17 17:58:46.218246+0100 TensorMac[44863:607287] Fatal error: 'try!' expression unexpectedly raised an error: Python exception: No module named 'matplotlib': file PythonKit/Python.swift, line 673
```

I'm running Xcode 12.1, have followed all the steps in [Installation.md](https://github.com/tensorflow/swift/blob/master/Installation.md) and installed the Swift for TensorFlow 0.11 Release Xcode toolchain. 

I'm able to import those libraries from the Pyton REPL:

```
$ python
Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import matplotlib
>>> 
```

Any thoughts?

**Comment by brettkoonce** [comment]
Loosely, xcode is using the system python and you are running a different version in your terminal:

```
let os = Python.import("os")
print(os.playgroundDescription)
```

     <module 'os' from '/usr/local/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py'>

install matplotlib with this version:

    cd /usr/local/Frameworks/Python.framework/Versions/3.8/bin
    ./python3 -m pip install matplotlib

**Comment by arielelkin** [comment]
Thanks for the pointer. I ended up fixing this by installing Python 3 and then doing `$ pip3 install matplotlib`
