### ISSUE TITLE
Compile error when build from source, with --xcode flag

### ISSUE THREAD

**Issue by aaaron7** [tensorflow/swift#57]
My Environment:
Mojava beta 8
Xcode 10 beta 5

I can successfully build swift for tensorflow with `utils/build-script --enable-tensorflow --release-debuginfo`,  but when I build with xcode support, which by following command:

```
utils/build-script --enable-tensorflow --release-debuginfo --xcode
```

then i encountered compile error as follows:

```
Build system information
error: Cycle in dependencies between targets 'complete-test' and 'swiftBasic'; building could produce unreliable results.
Cycle path: complete-test → sourcekitd → SourceKitService → swiftBasic → complete-test
Cycle details:
→ Target 'complete-test' has link command with output '/Users/uc/Documents/projects/github/build/Xcode-RelWithDebInfoAssert/swift-macosx-x86_64/RelWithDebInfo/bin/complete-test'
○ Target 'complete-test' has target dependency on Target 'sourcekitd'
→ Target 'sourcekitd' has target dependency on Target 'SourceKitService'
○ That command depends on command in Target 'SourceKitService': script phase “CMake Rules”
→ Target 'SourceKitService' has target dependency on Target 'swiftBasic'
○ That command depends on command in Target 'swiftBasic': script phase “CMake Rules”
→ Target 'swiftBasic' has target dependency on Target 'lib-Basic-8-UnicodeExtendedGraphemeClusters.cpp'
```

is there a bug with new build system? if so, how can i configure build-script to use legacy build system? 

Thanks.

**Comment by rxwei** [comment]
I'm unable to reproduce this build error on Mojave beta 8 and Xcode 10 beta 5. 

`build-script` generates an Xcode project that uses the legacy build system for me on Mojave. If that's not the case for you, you can always open `Swift.xcodeproj` and switch the build system in Xcode.
