### ISSUE TITLE
Project shutting down ?

### ISSUE THREAD

**Issue by suyashjoshi** [tensorflow/swift#609]
Hello,

Can you give this project to community so it's no longer Google owned (the repo and contributions etc) since it's shut down by Google I think?

**Comment by ArEnSc** [comment]
Can you reference where you found that the project was shutting down? I don't see that anywhere posted.

**Comment by ArEnSc** [comment]
Never mind the latest commit seemed to explain that

**Comment by BradLarson** [comment]
Thank you for the interest in carrying this forward.

There are multiple components that have come out of the Swift for TensorFlow project: Swift language enhancements, Swift components related to data science, Swift machine learning APIs, and Swift machine learning models. The language features should continue to live on outside of this project. The features supporting Python interoperability are part of the core Swift language now, and [PythonKit](https://github.com/pvieito/PythonKit) will continue to be available. Differentiable Swift has been upstreamed to the core Swift project and is currently [moving through the official Evolution process](https://forums.swift.org/t/differentiable-programming-for-gradient-based-machine-learning/42147/97). You can follow its progress and help steer its direction there.

Likewise, many of the supporting libraries will continue to be available, such as [swift-benchmark](https://github.com/google/swift-benchmark) or the [Swift Jupyter kernel](https://github.com/google/swift-jupyter).

The repositories that are being archived will contain the [Swift machine learning APIs](https://github.com/tensorflow/swift-apis), [machine learning models](https://github.com/tensorflow/swift-models), and [documentation](https://github.com/tensorflow/swift) that have been generated in the development of this project. As was said at the announcement meeting this morning, the community is free to fork these repositories (a number of forks already do exist) and continue the work on APIs and models that began here.

Our [mailing list](https://groups.google.com/a/tensorflow.org/d/forum/swift) will remain open, if you'd like to further discuss this with the broader community.

**Comment by suyashjoshi** [comment]
https://news.ycombinator.com/item?id=26117453

**Comment by suyashjoshi** [comment]
Ok thanks for the answer! May want to highlight in the readme that mailing list will remain open!
