### ISSUE TITLE
Running this branch of Swift with the included headers does not allow TensorFlow to be imported

### ISSUE THREAD

**Issue by theodinspire** [tensorflow/swift#61]
OS: Ubuntu 16.04
Build: 15 August, 2015

Documentation at the end of `Installation.md` is incorrect. Including these headers through the `swift -I /<path-to-toolchain>/usr/lib/swift/clang/include` command actually causes problems when trying to import TensorFlow, resulting in an error of redefinitions.

Reproduction steps:
1. Add the 15 Aug build to path
2. Run `swift -I /<path-to-toolchain>/usr/lib/swift/clang/include`
3. Enter `import TensorFlow`

Here is a sample error

```
error: /<directory/usr/lib/lldb/clang/6.0.0/include/module.modulemap:24:8: error redefinition of module '_Builtin_intrinsics'
module _Builtin_intrinsics [system] [extern_c] {
        ^

./usr/lib/swift/clang/include/module.modulemap:24:8: note previously defined here 
module _Builtin_intrinsics [system] [extern_c] {
        ^
…
```

**Comment by rxwei** [comment]
Thanks. This part of installation instructions are not up to date.

Are you able to run everything without specifying `-I /<path-to-toolchain>/usr/lib/swift/clang/include`?

**Comment by johndpope** [comment]
https://github.com/tensorflow/swift/issues/10#issuecomment-417010102
is there any reason documentation can't hard code to symlink?  seems easiest.
/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx

**Comment by theodinspire** [comment]
@rxwei I was able to run everything without the `-I` statement

**Comment by rxwei** [comment]
I removed it from the installation instructions.  Thanks for verifying!
https://github.com/tensorflow/swift/blob/master/Installation.md
