### ISSUE TITLE
not an issue - thoughts on swift matrix helpers / math libraries / Numeric operator overloading

### ISSUE THREAD

**Issue by johndpope** [tensorflow/swift#70]
I'm porting some python code and bumping up with some tech spike around some trivial matrix ops.

eg.
```python
   env_low = env.observation_space.low // Array 
    env_high = env.observation_space.high // Array 
    env_dx = (env_high - env_low) / n_states // divide array of floats by float - return new array

```

to swift / here's some code that will coerce a numpy array to native swift array.
✅

```swift

import Python

extension Array where Element == UInt8 {
    
    public init?(numpyArray: PythonObject) {
        /*
        guard let np = try? Python.attemptImport("numpy") else {
            return nil
        }
    
        guard Python.isinstance(numpyArray, np.ndarray) == 1 else {
            return nil
        }
        
        let numpyArray = numpyArray.astype(np.uint8)*/
        let numpyArraySize = Int(numpyArray.size)!
        let numpyArrayPointerAddress = UInt(numpyArray.__array_interface__["data"].tuple2.0)!
        let pointer = UnsafePointer<Element>(bitPattern: numpyArrayPointerAddress)!
        let bufferPointer = UnsafeBufferPointer(start: pointer, count: numpyArraySize)
        self.init(bufferPointer)
    }
}

// agnostic helper to subtract arrays - allowing  (env_high - env_low) 
func - <Element: Hashable>(lhs: [Element], rhs: [Element]) -> [Element]
{
    return Array(Set<Element>(lhs).subtracting(Set<Element>(rhs)))
}
```

but then using
subtract / multiply / divide etc - is not so straightforward. I'm not looking to do tensorflow ops on the graph - just some data wrangling. 

Using a swift library like surge - I can get first class operations on matrices using accelerate framework 
https://github.com/mattt/Surge

Arithmetic /sum /asum/ max / min / mean / meamg / measq etc
https://github.com/mattt/Surge/blob/master/Sources/Surge/Arithmetic.swift

although the linux users would obviously have reservations with any specific osx code.
So enter numpy -> 
numpy for swift may seem like a good answer - but interfacing with it is a bit of black box (without code completion). maybe some documentation could be built around this and backfilled into code completion?? 

I found this library by @sonsongithub  which seems like an attempted swift numpy port 
https://github.com/sonsongithub/numsw/tree/master/Sources/numsw/Matrix

related
https://github.com/mattt/Surge/issues/85

perhaps there's no we should use this / or that - as community will rally to build out the tools in due course - maybe it's a case of getting behind Surge to provide a shim for linux users which would run without the acceleration (4000 times slower).  @mattt - do you have any thoughts?

or is there something I'm missing? 

To add to discourse - in any third party framework - getting these to work with terminal app with frameworks is not so trivial.  so there's that to consider. https://github.com/JohnSundell/Marathon/issues/186

**Comment by johndpope** [comment]
this library seems to be trending for python arrays.
https://xarray.pydata.org/en/stable/

**Comment by rxwei** [comment]
We are not going to be able to add arithmetic operators to `Array` because they would conflict with array concatenation.
