### ISSUE TITLE
Compiler crash associated with uninitialized variables

### ISSUE THREAD

**Issue by LeegleechN** [tensorflow/swift#71]
Here is some sample code I attempted to compile. The code has a bug where I failed to assign a value to the `activation` parameter. Instead of giving me an error, the compiler crashes (details below).
 ```
import TensorFlow

func identity(_ a : Tensor<Float>) -> Tensor<Float> {
    return a
}

struct DenseLayer : Parameterized {
    @TFParameter var w: Tensor<Float>
    @TFParameter var b: Tensor<Float>
    var activation: (Tensor<Float>) -> Tensor<Float>
    
    init(inputSize: Int32, outputSize: Int32, activation : (Tensor<Float>) -> Tensor<Float> = identity) {
        w = Tensor(zeros: [inputSize, outputSize])
        b = Tensor(zeros: [outputSize])
    }
    
    func forward(_ input : Tensor<Float>) -> Tensor<Float>{
        return activation(input • w + b)
    }
}
```

I am running on Jupyter hosted in docker, using the instructions from [this tutorial](https://github.com/tensorflow/swift-tutorials).

When I attempt to compile the above code, my Jupyter kernel crashes with the following error message:

```
python: /home/swift-build/swift/lib/SILOptimizer/Transforms/SILMem2Reg.cpp:476: void (anonymous namespace)::MemoryToRegisters::removeSingleBlockAllocation(swift::AllocStackInst *): Assertion `ASI->getElementType().isVoid() && "Expected initialization of non-void type!"' failed.
Stack dump:
0.      While running pass #356 SILModuleTransform "TFDeabstraction".
1.      TFDeabstraction on function $S13__lldb_expr_710DenseLayerV9inputSize06outputF010activationACs5Int32V_AH10TensorFlow0J0VySfGALXEtcfC
2.      PromotableMemoryFinder::promoteToSSA
```

**Comment by rxwei** [comment]
@marcrasi would you like to take a look?

**Comment by marcrasi** [comment]
Yup, I'll take a look!

**Comment by rxwei** [comment]
Sorry we didn't get to triage your issue in time! Here are some updates:
- `Parameterized` and `@TFParameter` have been deprecated.
- Graph Program Extraction has been turned off. Swift for TensorFlow is much more usable (no crashers!) now.
- Please check out https://github.com/tensorflow/swift-apis and https://github.com/tensorflow/swift-models for best model building practice.
