### ISSUE TITLE
let keras = Python.import("keras")  ......Using TensorFlow backend.

### ISSUE THREAD

**Issue by johndpope** [tensorflow/swift#73]
Using TensorFlow backend.
Fatal error: 'try!' expression unexpectedly raised an error: Python exception: Traceback (most recent call last):
  File "/Users/jpope/miniconda3/envs/gymai/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/jpope/miniconda3/envs/gymai/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/jpope/miniconda3/envs/gymai/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/jpope/miniconda3/envs/gymai/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow17FunctionCallFrame14ConsumeRetvalsEPNSt3__16vectorINS_6TensorENS1_9allocatorIS3_EEEE
  Referenced from: /Users/jpope/miniconda3/envs/gymai/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: /Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/libtensorflow_framework.so
 in /Users/jpope/miniconda3/envs/gymai/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

is there a way to get this symbol into the  _pywrap_tensorflow_internal.so ?
do we need a special build ?

__ZN10tensorflow17FunctionCallFrame14ConsumeRetvalsEPNSt3__16vectorINS_6TensorENS1_9allocatorIS3_EEEE

sample project
https://github.com/johndpope/SwiftReinforce/commit/690c368b9129516715692873a6abed1498d68046

**Comment by johndpope** [comment]
I found a way forward / just edit config to use theano
`
 code $HOME/.keras/keras.json  tensorflow -> theano`

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Python exception: No module named cPickle

would be good to be able to dial up tensorflow python package here.

**Comment by johndpope** [comment]
Probably need a desingated repo for python / swift problems

if I try 
let torch = Python.import("torch") // pip install torch - I get this problem. 
I will capture this here and post solution in case I solve this. 

`Fatal error: 'try!' expression unexpectedly raised an error: Python exception: module compiled against API version 0xa but this version of numpy is 0x9: file /usr/local/src/swift-build/swift/stdlib/public/core/ErrorType.swift, line 185`

**Comment by johndpope** [comment]
fixed using insert

eg. ```swift

      sys.path.insert(0,path3)
        sys = Python.import("sys")
        print("INFO: macOS sysPath:", sys.path)  

    func importConda(){
        
        print("INFO: 🐍 conda environment:",environmentName)
        let  path2 = "/Users/\(NSUserName())/miniconda2/envs/\(environmentName)/lib/python2.7/site-packages/"
        sys.path.insert(0,path2)
        let  path3 = "/Users/\(NSUserName())/miniconda3/envs/\(environmentName)/lib/python2.7/site-packages/"
        sys.path.insert(0,path3)
        // N.B. use insert rather than append otherwise ran into problems
        // numpy version    //https://github.com/tensorflow/swift/issues/73 - numpy  1.8.0rc1

        print("INFO: sys path \n",path)


    }
```

**Comment by porterchild** [comment]
Were you able to import Keras? I used the sys.path.insert and that worked, but I get `ImportError: dlopen(/Users/porter/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow11NodeBuilderC1EN4absl11string_viewES2_PKNS_19OpRegistryInterfaceE`

**Comment by johndpope** [comment]
I made more instructions on getting up and running with miniconda https://github.com/johndpope/swifttorch

There’s a few gotchas with version mismatches and paths - try my xcodegen suggestion in above repo.

**Comment by bbvch13531** [comment]
Thanks johndpope. I get an idea after reading it and finally solved my problem. 

` pip3 install 'numpy==1.16.1' `

In my case it works.
