### ISSUE TITLE
Swift for TensorFlow Development Snapshot 2018-09-17” does not have a valid signature

### ISSUE THREAD

**Issue by LinMaris** [tensorflow/swift#75]
![image](https://user-images.githubusercontent.com/17720805/46257251-27441f00-c4e9-11e8-8e34-9d32dd847cff.png)

$ /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2018-09-17-a.xctoolchain/usr/bin/swift

It can work, 
but I can not swift -O xx.swift,   print `No module TensorFlow`

**Comment by LinMaris** [comment]
Ok, I can only use it like this first.
```
$ /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2018-09-17-a.xctoolchain/usr/bin/swift -O xx.swift
```

**Comment by dan-zheng** [comment]
You likely didn't add `swift` to your path. If you run `where swift`, it probably points to `/usr/bin/swift`.

To use the Swift for TensorFlow toolchain with command-line tools, add the toolchain to your path as follows:
```
$ export PATH=/Library/Developer/Toolchains/swift-latest/usr/bin:"${PATH}"
```

Alternatively, you can install [`swiftenv`](https://swiftenv.fuller.li/) and run the following:
```
swiftenv global tensorflow-DEVELOPMENT-2018-09-17-a
```

Then, `swift` should point to the TensorFlow toolchain. I'd personally recommend swiftenv!

**Comment by LinMaris** [comment]
@dan-zheng  It works, Thanks

**Comment by LinMaris** [comment]
Why are there no hints here?
![image](https://user-images.githubusercontent.com/17720805/46258897-f6251800-c503-11e8-9d69-77ff91e573c8.png)

**Comment by dan-zheng** [comment]
That bug is documented at [SR-8462](https://bugs.swift.org/plugins/servlet/mobile#issue/SR-8462).
Code completion for import declarations doesn’t support pure Swift modules yet. Some design/engineering is needed to support that.

**Comment by LinMaris** [comment]
@dan-zheng 非常感谢
