### ISSUE TITLE
I can not export a ML Model From TFiwS

### ISSUE THREAD

**Issue by LinMaris** [tensorflow/swift#76]
I learn from [swift-models](https://github.com/tensorflow/swift-models) and [swift-tutorials](
https://github.com/tensorflow/swift-tutorials), but I don't know how to produce ML Model from TFiwS

**Comment by rxwei** [comment]
If you'd like to dump the weights stored in a group of parameters, you can use Swift's encoding and decoding, though in the Swift `TensorFlow` library there's no APIs for serializing weights to a binary file yet. `Tensor` already implements `Codable` so any struct of tensors can get a derived conformance to `Codable`, and you can write manual serialization code for now.

If you'd like to export a model to a specific model format (e.g. `.savedmodel`), it's not in our scope right now but on the roadmap. Swift for TensorFlow's programming model allows tensor code and normal code to live side by side, and the notion is different from traditional models that are expressible in a domain-specific language and be serialized to a special format (like `.savedmodel`). We can support `.savedmodel` through protocol requirements that limit a model's methods to be TensorFlow graph-only, but this is going to constrain the expressiveness of model code.

**Comment by LinMaris** [comment]
@rxwei 
```
func lossAndGradient(for input: Tensor<Float>,
                     using model: IrisParameters,
                     labels: Tensor<Int32>) -> (Float, IrisParameters) {
    let (loss, (_, modelGrad)) =
        #valueAndGradient(loss(for:using:labels:), wrt: .0, .1)(input, model, labels)
    return (loss, modelGrad)
}
```
`#valueAndGradient` this is confused grammar,  I can not run this code, that will crash In my Xcode Project
Can I customize the backpropagation method by Tensor?
![image](https://user-images.githubusercontent.com/17720805/46610478-70c1e900-cb3d-11e8-8d2e-655823551ade.png)
![image](https://user-images.githubusercontent.com/17720805/46610563-ad8de000-cb3d-11e8-81b3-75463b6063c8.png)

**Comment by LinMaris** [comment]
@rxwei 
Why do I have to use the system python to run jupyter notebook for TFiwS, 

I have created python27 environment by Anaconda, but the kernel was dead.- .-

**Comment by rxwei** [comment]
Automatic differentiation is still work in progress. Jupyter and Python interoperability in general only supports the system python at the moment. All these components are in active development, and we'll welcome contributions if you are interested.

**Comment by rxwei** [comment]
For the latest examples of automatic differentiation and deep learning APIs, check out https://github.com/tensorflow/swift-apis. I'm going to close this issue since we'll be developing model serialization/deserialization in the deep learning library.
