### ISSUE TITLE
Optimize for Speed [-O]  can not work

### ISSUE THREAD

**Issue by LinMaris** [tensorflow/swift#77]
I can execute `swift -O xx.swift` by ternimal, and get correct result.
but when I follow [this method](https://github.com/tensorflow/swift/issues/10#issuecomment-385167803), I configured my Xcode project.
Once I execute my project, I will get an error.
```
let x = Tensor<Float>([[1, 2], [3, 4]])
print(x)
```
![image](https://user-images.githubusercontent.com/17720805/46341455-b0369400-c66a-11e8-8a92-c43feb16db4d.png)

Whether or not I set this, `Optimize for Speed [-O] `, TensorFlow can't work.

**Comment by dan-zheng** [comment]
Which macOS toolchain did you download? I see `eGPUOverrides` in the error message, which makes me a bit suspicious.

**Comment by LinMaris** [comment]
I create a empty macOS project, and run it with default toolchain
```
[default] Unable to load Info.plist exceptions (eGPUOverrides)
```
It still prints in my console.
![image](https://user-images.githubusercontent.com/17720805/46356768-fb19d100-c695-11e8-9f06-68449e02d40e.png)

**Comment by rxwei** [comment]
It appears that you used a Swift for TensorFlow development snapshot (which is correct), not the default toolchain.

Let me try to reproduce this and get back to you.

**Comment by LinMaris** [comment]
@rxwei 
Firstly, No matter which toolchain I choose, this log still exist
```
[default] Unable to load Info.plist exceptions (eGPUOverrides)
```
Secondly, I choose this chain `Swift for TensorFlow development snapshot 208-09-17`, run this code. that will crash.
```
let x = Tensor<Float>([[1, 2], [3, 4]])
print(x)
```
![image](https://user-images.githubusercontent.com/17720805/46363470-b39b4100-c6a5-11e8-8589-1e4ae4611cc6.png)

**Comment by rxwei** [comment]
I'm unable to reproduce this error. Here's how I set up a "Command Line Tool" project in Xcode in project settings:
- Set "Runpath Search Paths" to 
    `/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2018-09-17-a.xctoolchain/usr/lib/swift/macosx`
- Set "Library Search Paths" to
    `/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2018-09-17-a.xctoolchain/usr/lib/swift/macosx`
- Set "Swift Compiler - Code Generation" - "Optimization Level" to "Optimize for Speed [-O]"

Then I can build and run a trivial program in `main.swift`:
```swift
import TensorFlow

var x = Tensor<Float>([[1, 2], [3, 4]])

for _ in 1...5 {
  x += x • x
}

print(x)
```

**Comment by LinMaris** [comment]
@rxwei  you are right, I set up a "Command Line Tool" project in Xcode and that works, NO Crash

I set up the "Cocoa app" project before. that crash. :)

thanks
