### ISSUE TITLE
A crash log

### ISSUE THREAD

**Issue by aiden213** [tensorflow/swift#78]
Hi,

I used the MacOS 10.14 and the Xcode 10. After installing the swift for tensorflow, I got a very long crash log. 
[crashlog.txt](https://github.com/tensorflow/swift/files/2444705/crashlog.txt)

<img width="912" alt="screen shot 2018-10-03 at 8 45 10 pm" src="https://user-images.githubusercontent.com/20410568/46450192-4511be00-c74d-11e8-8af4-f5b4bdc32bf1.png">

<img width="1072" alt="screen shot 2018-10-03 at 8 40 26 pm" src="https://user-images.githubusercontent.com/20410568/46450091-be5ce100-c74c-11e8-8d50-95fbc0097f2b.png">

**Comment by rxwei** [comment]
This is a bug in Xcode and/or LLDB. We recommend using [Swift Jupyter](https://github.com/google/swift-jupyter) for development because it's more stable.

**Comment by aiden213** [comment]
All right. thanks for your reply. 👍
