### ISSUE TITLE
Fatal error in the Swift-Jupyter

### ISSUE THREAD

**Issue by aiden213** [tensorflow/swift#80]
Hi, there!
I follow the Installation Instructions and step by step on my MAC.
Everything is perfect. I can see that "Registered kernel 'Swift' as 'swift'!". I also can find the "swift" button in the jupyter notebook. However, there was a fatal error when I create a new swift.
Is there someone could tell what is wrong with that. Thanks so much!
By the way, I found the swift-tensorflow the latest version 2018-10-05, it worked on the Xcode playgroud. Great job!
<img width="1025" alt="screen shot 2018-10-11 at 7 31 53 pm" src="https://user-images.githubusercontent.com/20410568/46843125-811cd280-cd8e-11e8-9e3b-f2917521c3bd.png">
<img width="915" alt="screen shot 2018-10-11 at 7 32 20 pm" src="https://user-images.githubusercontent.com/20410568/46843132-8712b380-cd8e-11e8-8891-6472475aadac.png">
<img width="228" alt="screen shot 2018-10-11 at 7 32 34 pm" src="https://user-images.githubusercontent.com/20410568/46843134-88dc7700-cd8e-11e8-93f5-23dfda014a5a.png">

**Comment by marcrasi** [comment]
Hi!

The "Fatal Python error: PyThreadState_Get: no current thread" message that shows up in the console looks pretty suspicious. Based on some searching, it seems to have something to do with loading libraries that are linked against different versions of python (e.g. https://stackoverflow.com/questions/15678153/homebrew-python-on-mac-os-x-10-8-fatal-python-error-pythreadstate-get-no-cu).

The lldb library seems like the most likely culprit. I'd be curious about the output of the following commands on your system:
```
otool -L <directory containing your venv>/venv/bin/python
ls -la <directory containing your venv>/venv
otool -L /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2018-10-05-a.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Resources/Python/lldb/_lldb.so
```
They might reveal that _lldb.so is picking up a different python from your venv's python interpreter.

Alternatively, maybe some of the solutions suggested in the stackoverflow will help. I'm not sure how useful they will be, since I can't repoduce the problem myself.

**Comment by aiden213** [comment]
Hello!
Thanks for the information about my "Fatal Python error".
Exactly, there was two Python version in my MacOS, 3.6.x and 2.7.x. It should be the lldb library link the Python 3.6.x.
And now, I try to use the swift for jupyter in Ubuntu 16.04. Everything is good, swift for jupyter is work. 
However, there is something wrong with the rich output the swift.
I saw the usage instructions said that: "Do not install them on the virtualenv from the Swift-Jupyter installation instructions. Swift's Python interop talks to your system Python."
Thus, I use the command
"pip2 install numpy"
"pip2 install matplotlib==2.2.3"
"pip2 install ipykernel==4.9.0"
Hope this will help improve the installation instructions. :)
And the error is
error: <REPL>:1:10: error: use of unresolved identifier 'Python'
let np = Python.import("numpy")
I try to add new user to reinstall because before I use the anaconda2 to create a new env.

**Comment by aiden213** [comment]
Now, everything is perfect work in my Ubuntu 16.04 LTS. My system default version is python 2.7.15. I share my install steps and hope this is useful:
1. you need to update your pip version from 8.x to 18.1: pip install -U pip
2. pip2 install ipykernel==4.9.0
3. pip2 install matplotlib==2.2.3
4. pip2 install pandas
5. pip2 install numpy
6. sudo apt-get install python-tk (I need to install this, and the official installation instruction didn't show that, but I think it is important for someone.)
7. virtualenv venv
. venv/bin/activate
pip2 install jupyter # Must use python2, because LLDB doesn't support python3.
8. you need go into the "swift-jupyter-master" folder which download from the "google/swift-jupyter". And you also need to check you are in the "venv" such as: "(venv) swift@lyt:~$" and Register the kernel with jupyter:
(venv) swift@lyt:~/Downloads/swift-jupyter-master$ python register.py --sys-prefix --swift-toolchain /home/swift/Downloads
You will see 'Swift' as 'swift' at the end.
9. (venv) swift@lyt:~$ jupyter notebook.
Done! It should be work! Enjoy the swift for tensorflow, for jupyter and Rich output! :)

**Comment by rxwei** [comment]
Closing this since the issue has been resolved.
