### ISSUE TITLE
"Tensor op instruction has no device string"

### ISSUE THREAD

**Issue by bokertov** [tensorflow/swift#81]
I downloaded the latest version (built on 10/13), and tried the example. But it failed immediately:

$ swift
Welcome to Swift version 4.2-dev (LLVM d1ad27a0c9, Clang 528407c5c8, Swift 27d53eae28).
Type :help for assistance.
  1> import TensorFlow
  2> var x = Tensor<Float>([[1,2], [3,4]])
Assertion failed: (attr.hasValue() && "Tensor op instruction has no device string"), function getDeviceString, file /usr/local/src/swift-build/swift/lib/SILOptimizer/Mandatory/TFDevicePartition.cpp, line 43.

**Comment by rxwei** [comment]
We are working on enabling non-optimized complication mode. In the meantime, you can turn on `swift -O`.

**Comment by bokertov** [comment]
How do we turn on "swift -O" in REPL?

**Comment by rxwei** [comment]
When you run the REPL, run `swift -O` instead of `swift`.

**Comment by pb-z** [comment]
I have same issue even run with `swift -O`

> Welcome to Swift version 4.2-dev (LLVM d1ad27a0c9, Clang 528407c5c8, Swift 27d53eae28).
> Type :help for assistance.
>   1> import TensorFlow
>   2> var x = Tensor<Float>([[1, 2], [3, 4]])
> Assertion failed: (attr.hasValue() && "Tensor op instruction has no device string"), function getDeviceString, file /usr/local/src/swift-build/swift/lib/SILOptimizer/Mandatory/TFDevicePartition.cpp, line 43.

**Comment by bokertov** [comment]
Yes, "swift -O" doesn't work. Same error.

**Comment by rxwei** [comment]
Fixed in 2018-10-17 toolchain.

```console
  1> import TensorFlow
  2> var x = Tensor<Float>([[1, 2], [3, 4]])
x: TensorFlow.Tensor<Float> = [[1.0, 2.0], [3.0, 4.0]]
```
