### ISSUE TITLE
Xcode 10, Playground crash when TensorFlow Toolchain selected

### ISSUE THREAD

**Issue by iDevPro** [tensorflow/swift#82]
Hello, I have issue after install precompiled TensorFlow for swift
My system: 
- OS X 10.14 (18A391)
- Xcode 10.0 (10A255)

https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2018-10-17-a-osx.pkg - crash in Playground, in REPL this work

https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2018-08-15-a-osx-cuda.pkg - crash in REPL (no CUDA9 work libs found)

**Comment by rxwei** [comment]
Playground support has been unstable. The primary prototyping environment we support and recommend is [Jupyter notebooks](https://github.com/google/swift-jupyter).

Could you try an older toolchain, e.g. [2018-10-05](https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2018-10-05-a-osx.pkg)?

**Comment by iDevPro** [comment]
> Playground support has been unstable. The primary prototyping environment we support and recommend is [Jupyter notebooks](https://github.com/google/swift-jupyter).

Hmm, Jupyter notebook + Swift + TensorFlow/Swift ?

**Comment by rxwei** [comment]
Not sure what you mean exactly. Our [tutorials](https://github.com/tensorflow/swift-tutorials) are based on Jupyter, not Xcode.

**Comment by rxwei** [comment]
I'm going to close the issue for now. Our recommended development environment is Google Colab (see [instructions](https://github.com/tensorflow/swift/blob/master/Usage.md#colaboratory)), and we will not fix playground issues in the near term.
