### ISSUE TITLE
Crash in SILVerifier

### ISSUE THREAD

**Issue by ppiech** [tensorflow/swift#85]
I get a crash trying to compile following code using toolchain from 2018-10-17 on a mac:

```
import TensorFlow

public struct MyParameters : ParameterGroup {
    @inlinable
    public init() {}

    public var theta = Tensor<Float>(randomNormal: [2, 1])
}

@inlinable
public func computeCost(for input: Tensor<Float>, using model: MyParameters, labels: Tensor<Float>) -> Float {
    let prod = matmul(input, model.theta)
    let J = (prod - labels).squared().mean() * 0.5
    return J
}

func lossAndGradient(for input: Tensor<Float>,
                     using model: MyParameters,
                    labels: Tensor<Float>) -> (Float, MyParameters) {
   let (loss, (_, modelGrad)) =
       #valueAndGradient(computeCost(for:using:labels:), wrt: .0, .1)(input, model, labels)
   return (loss, modelGrad)
}

```

0.	Program arguments: /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2018-10-17-a.xctoolchain/usr/bin/swift -frontend -interpret test.swift -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -O -color-diagnostics -module-name test
1.	While verifying SIL function "@AD__$s4test11computeCost3for5using6labelsSf10TensorFlow0G0VySfG_AA12MyParametersVAItF__primal_src_0_wrt_0_1".
 for 'computeCost(for:using:labels:)' at test.swift:11:8
0  swift                    0x0000000110161028 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x00000001101602a5 llvm::sys::RunSignalHandlers() + 85
2  swift                    0x0000000110161632 SignalHandler(int) + 258
3  libsystem_platform.dylib 0x00007fff75700f5a _sigtramp + 26
4  libsystem_platform.dylib 0x0000000112e3c314 _sigtramp + 2641605588
5  libsystem_c.dylib        0x00007fff7549e1ae abort + 127
6  swift                    0x000000010d400559 (anonymous namespace)::SILVerifier::_require(bool, llvm::Twine const&, std::__1::function<void ()> const&) + 633
7  swift                    0x000000010d40f8be swift::SILInstructionVisitor<(anonymous namespace)::SILVerifier, void>::visit(swift::SILInstruction*) + 49518
8  swift                    0x000000010d4022cc (anonymous namespace)::SILVerifier::visitSILBasicBlock(swift::SILBasicBlock*) + 1196
9  swift                    0x000000010d3fc857 swift::SILFunction::verify(bool) const + 7799
10 swift                    0x000000010d3ff933 swift::SILModule::verify() const + 211
11 swift                    0x000000010c4e514f performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 11679
12 swift                    0x000000010c4e131d swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3021
13 swift                    0x000000010c4935ae main + 686
14 libdyld.dylib            0x00007fff753f2015 start + 1
Abort trap: 6

**Comment by rxwei** [comment]
Working to fix this. We'll release a new toolchain next week!

**Comment by ppiech** [comment]
Thank you, i look forward to it!

**Comment by rxwei** [comment]
Fixed in [the 2018-11-21 toolchain](https://github.com/tensorflow/swift/blob/master/Installation.md).
