### ISSUE TITLE
Xcode debugger variable values not available on Swift for TensorFlow toolchain

### ISSUE THREAD

**Issue by golmschenk** [tensorflow/swift#89]
When using the Swift for TensorFlow Development Snapshot (2018-12 04) toolchain, it seems variable values do not appear in the Xcode debugger. Note, this is for regular Swift variables, not TensorFlow values.

For example, running my code with the standard Swift toolchain and stopping at a breakpoint, the variable values appear as:
<img width="382" alt="screen shot 2018-12-18 at 11 47 21 am" src="https://user-images.githubusercontent.com/1691031/50169562-d0fea500-02bb-11e9-8c3e-37ff39115bfe.png">
However, with the Swift for TensorFlow toolchain, the same code results in:
<img width="382" alt="screen shot 2018-12-18 at 11 47 46 am" src="https://user-images.githubusercontent.com/1691031/50169613-e8d62900-02bb-11e9-97a9-5cbfc7f60191.png">

Is this expected based on how the Swift for TensorFlow toolchain is designed? Am I just missing some configuration needed to resolve this? Thank you for your time!

**Comment by rxwei** [comment]
> Is this expected based on how the Swift for TensorFlow toolchain is designed?

This is not expected.  I suspect this is because we have not upgraded LLDB for a while so the LLDB in our pre-built toolchains is about two months older than the compiler. We'll make sure to sync the versions of LLDB and Swift in our next toolchain build.

**Comment by golmschenk** [comment]
I tested several of the pre-built Xcode 10 toolchains available and found that most have this problem. A few provided _some_ variable values, but not all of them. However, I found that this problem only arises with the new build system. The Xcode legacy build system shows the full details of the variables.

**Comment by rxwei** [comment]
This is a known Xcode bug when it interacts with open source Swift toolchains. In fact, the latest toolchain requires you to use the legacy build system, unfortunately.

**Comment by txbad** [comment]
Does this problem resolved?
I encountered this problem, and the warning info as following:
**Cannot load Swift type information; AST validation error in "LeNet_MNIST": The module file format is too new to be used by this version of the debugger.AST validation error in "ImageClassificationModels": The module file format is too new to be used by this version of the debugger.AST validation error in "Datasets": The module file format is too new to be used by this version of the debugger.AST validation error in "Datasets": The module file format is too new to be used by this version of the debugger.AST validation error in "ImageClassificationModels": The module file format is too new to be used by this version of the debugger.**

my Xcode version is: 11.3
swift for tensorflow is: development snapshot 2020-01-30

what's the solution to this problem?

**Comment by imkerberos** [comment]
+1

**Comment by dan-zheng** [comment]
> Does this problem resolved?
> I encountered this problem, and the warning info as following:
> **Cannot load Swift type information; AST validation error in "LeNet_MNIST": The module file format is too new to be used by this version of the debugger.

This issue is tracked at SR-12127. It's actually an issue in Xcode: Xcode uses system `lldb` instead of `lldb` from the active toolchain. The occurs even for [swift.org/download](https://swift.org/download) toolchains and isn't specific to Swift for TensorFlow.

Unfortunately, our team can't help fix this issue since Xcode is closed source. I'll leave this issue open until SR-12127 is fixed.

**Comment by porterchild** [comment]
Not sure if this is directly related, but going from the 2/19/2020 toolchain to the 3/4/2020 toolchain makes it so breakpoints sometimes don't work correctly for me. What happens is it stops momentarily at the breakpoint, but then continues without any input for a second or two and stops with "Program ended with exit code: -1".
