### ISSUE TITLE
EnableIPythonDisplay.swift error

### ISSUE THREAD

**Issue by eldardamirov** [tensorflow/swift#94]
Hello! Recently I've installed Swift for Tensorflow on Jupyter as it is described in one of your guides here (all steps were followed). All seemed to be working properly (tried several examples), however when I've tried to install Rich Output - following error was encountered:
![2019-01-04 22 43 42](https://user-images.githubusercontent.com/29756748/50707551-3bf8fb80-1072-11e9-87ac-87f3fa048069.png)
What I can do about that? Thanks in advance:)

CONFIGURATION:
macOS High Sierra 10.13.5, Xcode 10.0, Latest toolchain available as for 5-th January 2019, MacBook Pro Late 2011;
"which python": "/usr/bin/python"
All the necessary libs were installed.
That is folder tree, error happened to be in Untitled1.ipynb;
├── Untitled.ipynb
├── Untitled1.ipynb
├── swift-jupyter
│   ├── CONTRIBUTING
│   ├── EnableIPythonDisplay.swift
│   ├── KernelCommunicator.swift
│   ├── LICENSE
│   ├── README.md
│   ├── Untitled.ipynb
│   ├── docker
│   │   ├── Dockerfile
│   │   └── run_jupyter.sh
│   ├── register.py
│   ├── screenshots
│   │   ├── display_matplotlib.png
│   │   └── display_pandas.png
│   ├── swift_kernel.py
│   ├── swift_shell
│   │   ├── __init__.py
│   │   └── __pycache__
│   └── test
│       └── test.py
├── untitled.txt

**Comment by marcrasi** [comment]
Hi!

Based on the error message, I'm guessing that you have a different version of Jupyter on your system whose API is incompatible EnableIPythonDisplay. If you help me figure out which version of Jupyter you have, I'll update EnableIPythonDisplay to be compatible or I'll update the installation instructions to ensure you have the right version.

To find out the version on your system, try running `pip show ipykernel` and `pip show jupyter-client`, NOT in the virtualenv that the instructions asked you to create. Also try running this code in a Swift notebook:
```
import func Darwin.C.dlopen
dlopen("libpython2.7.so", RTLD_NOW | RTLD_GLOBAL)
import Python
print(Python.import("jupyter_client").version_info)
```

The results on my system are:
```
marcrasi-macbookpro:~ marcrasi$ pip show ipykernel
Name: ipykernel
Version: 4.8.2
Summary: IPython Kernel for Jupyter
Home-page: http://ipython.org
Author: IPython Development Team
Author-email: ipython-dev@scipy.org
License: BSD
Location: /Users/marcrasi/Library/Python/2.7/lib/python/site-packages
Requires: jupyter-client, tornado, traitlets, ipython
Required-by:
marcrasi-macbookpro:~ marcrasi$ pip show jupyter-client
Name: jupyter-client
Version: 5.2.3
Summary: Jupyter protocol implementation and client libraries
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /Users/marcrasi/Library/Python/2.7/lib/python/site-packages
Requires: tornado, jupyter-core, traitlets, pyzmq, python-dateutil
Required-by: ipykernel
```
and the result from the Swift code is `(5, 2, 3)`.

Possibly installing those versions on your system will fix it.

**Comment by marcrasi** [comment]
Oh by the way, I just ran into the error that you posted while playing around with the kernel on a system with jupyter-client 5.2.4. So I'll see if I can make EnableIPythonDisplay compatible with 5.2.4. Information about your versions would still be helpful, in case you have yet a different version.

**Comment by marcrasi** [comment]
Upon further investigation, this error actually happens when your Swift kernel is configured to interop with Python 3. A quick fix is to replace `key: JupyterKernel.communicator.jupyterSession.key)` in EnableIPythonDisplay.swift with `key: Python.bytes(JupyterKernel.communicator.jupyterSession.key, "utf8"))`.

Unfortunately, that fix breaks it in Python 2. I will work on making a more proper fix that works in both pythons, and then I'll commit it.

**Comment by marcrasi** [comment]
https://github.com/google/swift-jupyter/pull/21 should fix this!
