### ISSUE TITLE
Adding Beta distribution support

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/swift#95]
I recently started porting a project to S4TF so I can experiment with it and wanted to contribute parts of that to the main codebase. For example, I added support for sampling from a Beta distribution which could go in the Random module. However, I bumped into a small Swift-related issue that I'm not sure how to best handle.

I can create a Beta distribution over Float or Double, for example, but when I try to generalize it over `BinaryFloatingPoint` as the rest of the S4TF distributions do, I cannot. The reason is I need to use the `log` function when sampling and it's not defined over `BinaryFloatingPoint`, but over `Float`, `Double`, and `Float80` separately. What is a good/standard way to deal with this kind of situation in Swift?

Thanks!

**Comment by eaplatanios** [comment]
Thanks Richard! I created a topic [here](https://forums.swift.org/t/generalizing-floating-point-math-operators-over-the-binaryfloatingpoint-protocol/19478). In the meantime, are you interested in a PR for the non-generalized version of the Beta distribution?

**Comment by rxwei** [comment]
> In the meantime, are you interested in a PR for the non-generalized version of the Beta distribution?

Yes!  Starting with just `Float` is totally fine.

**Comment by eaplatanios** [comment]
Nice. I added a PR [here](https://github.com/apple/swift/pull/21829), so I'll close this. :)
